### ISSUE TITLE
Errors during mordred config file consumption #128

### ISSUE THREAD

**Issue by Deepayan-Ghosh** [chaoss/grimoirelab-sirmordred#129]
I tried to run mordred with the mordred config file in https://grimoirelab.gitbooks.io/tutorial/mordred/a-grimoirelab-dashboard-in-one-step.html, but I get errors like `('Wrong section param:', 'general', 'sleep')`, `('Wrong section param:', 'general', 'kibana')` and `Error while consuming configuration:  ('Wrong section param:', 'es_enrichment', 'studies')`. It is here in this line: 
https://github.com/chaoss/grimoirelab-mordred/blob/master/mordred/config.py#L623 where we compare the params in cfg file and the `params_general`, which does not have the fields `kibana`, `sleep`, etc that raises the error. So either the documentation is old or there is problem is the `params_general` variable.

**Comment by olblak** [comment]
@Deepayan-Ghosh those options were (re)moved in the latest version,

Delete sleep and  kibana from 'general'
and move 'studies' from es_enrichment to the git backend section [Doc](https://github.com/chaoss/grimoirelab-elk/blob/master/doc/studies.md#running-studies-from-mordred)

**Comment by olblak** [comment]
And based on the version you are using, you can have a look to this (file)[https://github.com/chaoss/grimoirelab-mordred/blob/18.04-01/doc/config.md]

**Comment by jgbarah** [comment]
Yes. Thanks @olblak. I have to update the tutorial (leaving this open until I can fix that).

**Comment by valeriocos** [comment]
Fixed time ago, no errores in the PRD environments.
