### ISSUE TITLE
Why menu.yml is needed

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sirmordred#136]
If I've understood right, there should be a default `menu.yml` file as part of `grimoire-mordred` Python package. But it seems there is not, and `mordred` command still requires a `menu.yml` in the folder where it's executed from:
```
Exception in thread Global tasks:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_manager.py", line 76, in run
    task = tc(self.config)
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_panels.py", line 61, in __init__
    with open(TaskPanelsMenu.MENU_YAML, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'menu.yaml'
```

Wouldn't it be nice if `mordred` would use the existing [menu.yml](https://github.com/chaoss/grimoirelab-mordred/blob/master/menu.yaml) if no other is provided?

**Comment by jgbarah** [comment]
This is a good point. I can work to solve this.

Thinking about the underlying process, I think it would make more sense to include it in the Kidash module, including the code to upload it, and just call it from Mordred.

@acs what do you think?

**Comment by acs** [comment]
> @acs what do you think?

I like the approach!

**Comment by valeriocos** [comment]
@jsmanrique @jgbarah do you have info about this issue? thanks

**Comment by jsmanrique** [comment]
What might help you @valeriocos ?

**Comment by valeriocos** [comment]
Thank you for the quick reply @jsmanrique . Do you still have this issue?
I asked the Ops team and they said that the menu.yml is not uploaded manually when deploying

**Comment by jsmanrique** [comment]
I think it can be closed @valeriocos
