### ISSUE TITLE
Perceval exceptions cause Mordred steps fails

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sirmordred#141]
Trying to run some Meetups groups analysis with Mordred, I get exceptions related with "forbidden items" from the Meetup API (depending on group configuration).

These issues cause errors in the threads running in Mordred, and that some following steps, like enriched index creation, fail.

Could Mordred handle that? Or is it a [Grimoire ELK](https://github.com/chaoss/grimoirelab-elk) issue?

**Comment by sanacl** [comment]
How can this be reproduced @jsmanrique ?

**Comment by jsmanrique** [comment]
Well, I think it was preparing the UbuCon Europe dashboard:
https://gitlab.com/jsmanrique/grimoirelab-demos/tree/master/UbuConEU2018

My fault I haven't save the config that caused the issue

**Comment by valeriocos** [comment]
This should be related to token permissions, however if the bug cannot be reproduced, it is difficult to evaluate and prepare a fix.

Let's close this issue @jsmanrique @sanacl . In case it pops up again, we will handle it.
