### ISSUE TITLE
Doubt about how to configure GrimoireLab / mordred.cfg

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sirmordred#145]
I am deploying a new demo of GrimoireLab and I would like to test affiliations information management.

As first step, I've seen there are dedicated params in mordred.cfg about this. I've been reading the [docs](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/doc/config.md). But, it's not clear for me if which params I need to touch. Let me explain why.

If I've understood right, `affiliate`, `load_orgs`, and `orgs_file`, are the main params. And I plan to use this [orgs.json](https://github.com/chaoss/grimoirelab/blob/master/docker/orgs.json) file as data source:

And this is what the doc says:
```
affiliate (bool: True): Affiliate identities to organizations (Required)
load_orgs (bool: False):
orgs_file (str: None): File path with the organizations to be loaded in Sortinghat
```

So, without any further docs (I've not found anything else about these params anywhere), I think the values should be:
```
affiliate: True
load_orgs: True
orgs_file: orgs.json
```

But, then, I check current examples provided in the [main GrimoireLab repository](https://github.com/chaoss/grimoirelab) ([1](https://github.com/chaoss/grimoirelab/blob/master/docker/mordred-infra.cfg), [2](https://github.com/chaoss/grimoirelab/blob/master/docker/mordred-project.cfg)) and I see this:
```
affiliate: True
load_orgs: false
orgs_file: orgs.json
```

Could someone clarify why or how is the right way to work?

My objective is that at least, people committing using a corporate account email domain are rightly affiliated.

Thanks!

**Comment by sanacl** [comment]
It is not well documented @jsmanrique . The `affiliate` parameter allows to executiong of the SortingHat method `affiliate` which uses the available information (in the database) to guess the organization affiliation for each identity. 

The other two parameters are thought to allow to load new organizations based on a file. So, you could have affiliate set to True and the load_orgs set to False, but this way the json file would not be loaded into the identities database.

Let me know whether you understand my explanation :)

**Comment by jsmanrique** [comment]
Thanks @sanacl. Understood. So based in your explanation, the documented configuration in GrimoireLab tutorial makes no sense:
```
affiliate: True
load_orgs: false
orgs_file: orgs.json
```

I mean, what's the sense of setting `load_orgs` to `false` (it won't load any organizations json file), and set an `orgs_file`?

**Comment by sanacl** [comment]
> Thanks @sanacl. Understood. So based in your explanation, the documented configuration in GrimoireLab tutorial makes no sense:
> 
> ```
> affiliate: True
> load_orgs: false
> orgs_file: orgs.json
> ```
> 
> I mean, what's the sense of setting `load_orgs` to `false` (it won't load any organizations json file), and set an `orgs_file`?

The only point of doing that is no loading again data that is already loaded... But yes, it makes the explanation more complex and it is not well explained

**Comment by sanacl** [comment]
I guess we can close this ticket @jsmanrique

**Comment by jjmerchante** [comment]
Closing this ticket because the question is solved.
