### ISSUE TITLE
Menu set up as a phase (feature request) 

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sirmordred#147]
Currently, Mordred tries always to set up a sidebar menu for Kibiter / Kibana. 

I don't need that menu, so wouldn't it be nice having that as an optional phase in the Mordred set up file?

**Comment by valeriocos** [comment]
Sorry for the late reply @jsmanrique , @dlumbrer do you think it's possible?

**Comment by sanacl** [comment]
@jsmanrique do u think this is interesting for the current version?

**Comment by jsmanrique** [comment]
It would be interesting if you are interested in running this with a Kibana instance instead of Kibiter
