### ISSUE TITLE
Is there any way to make joint query from git and gerrit at the same time?

### ISSUE THREAD

**Issue by zhuqianbin** [chaoss/grimoirelab-sirmordred#148]
Hi, I want to know if there any way to check the git commit is pushed to Gerrit. I think it as follows:
1. for each git commit id, query it in gerrit index;
2. if the commit id is found, we can label it reviewed;
3. Or, we take it as non-reviewed;
Is there any way to get it?

**Comment by zhuqianbin** [comment]
Thank you for your immediate reply.

For this method: Create an ES alias joining the indexes

I tried to create an aliases including git and gerrit indices, but aliases can’t be indexed. That’s to say, it cannot be seen from Kibana. My kibana and ES are all latest version.

Can you please give me advice on how to get it on this way?

Thanks!

**Comment by sanacl** [comment]
I'm closing this ticket folks, if you have more comments about this feel free to open it again.
