### ISSUE TITLE
Mordred should remove repositories not included in the projects file

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#160]
In order to offer a better interaction with the user, the system must keep updated the enriched indexes based on the projects.json file. The update process is not 100% done as data sources are never removed from the enriched indexes even the they are deleted from the file.

These feature request is aimed to make Mordred smart enough to remove repositories when they are deleted from the project.json file.

**Comment by valeriocos** [comment]
Sorry for the late reply @sanacl . There were internal discussions to decide whether to (i) keep old data not listed in the projects.json anymore or (ii) update the indexes with the latest info. At the end, (i) was selected. Now old repositories in the projects.json can be ignored by adding `--filter-no-collection=true` (more info at: https://github.com/chaoss/grimoirelab-sirmordred#projectsjson)
