### ISSUE TITLE
Docker container logs should receive the all.log file

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#161]
The way dockerize applications log messages is via sending the logs via stdout and sterr. So, for Mordred it would be great if those logs are redirected that way directly from all.log instead so they could be available via `docker logs` command.

**Comment by filmaj** [comment]
The docker container, though, is revisioned over here, right? https://github.com/chaoss/grimoirelab

Or are you talking about the docker stuff in this repo?

If about the docker container that I believe is the former, then that dockerfile's shell script doesn't terminate and would remain printing out the stdout from the `mordred` binary. So from that perspective, as long as mordred prints to stdout the contents of all.log, I think we're OK.

Does that sound right? If so, I can put together a PR for this.

**Comment by sanacl** [comment]
@filmaj sorry for not attending your request. 

Currently there are two ways of using containers with Grimoirelab. One of them includes all the components in a single docker container. The other method uses different containers launched via Docker Compose. E.g, the Mordred docker container is defined at https://github.com/chaoss/grimoirelab-sirmordred/tree/grimoirelab-0.2.32/docker

Said that. I think this is no longer needed so I'm closing this issue.
