### ISSUE TITLE
"Missing mbox index" on page load

### ISSUE THREAD

**Issue by filmaj** [chaoss/grimoirelab-sirmordred#164]
I have set up my own Grimoirelab instance via the handy Docker container.

I only have a couple of GitHub data sources defined in my `projects.json`.

When I load Grimoirelab I see the following warnings at the top of the page:

<img width="1500" alt="screen shot 2018-06-26 at 11 16 11 am" src="https://user-images.githubusercontent.com/52645/41932705-5836ba02-7947-11e8-934d-1d9b28a364a2.png">

Can I do anything with my configuration to avoid this warning?

Thanks for any info! I am also happy to send a PR to fix stuff up for the tutorial/docs to reflect what I learn :)

**Comment by jgbarah** [comment]
Have a look at your `dashboard.cfg` file. By default it includes a section for mail archives. You could remove it entirely.

We need some code that ignores sections for which there are no repos, but that's not implemented yet.

**Comment by filmaj** [comment]
Awesome. I ended up removing the `[pipermail]` section from `/dashboard.cfg` in the docker container and that fixed the "mbox" warning. I ended up adding "git" data sources so that warning went away as well!

Do we want to transform this issue into a feature request / enhancement, then, to track the implementation of "code that ignores sections for which there are no repos" ? I am not super familiar with what this means, so feel free to edit the issue if you wish (or you can file a new one, I suppose, as well).

**Comment by filmaj** [comment]
Closing this issue, I consider it resolved.
