### ISSUE TITLE
[config] Duplicate logic for generating documentation

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-sirmordred#181]
@sanacl , @acs there is some code that seems to target the same goal:
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/config.py#L732
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/config.py#L537
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/cfg_generator

If this is the case, I would propose to keep just one of the solutions above. We could try to close this ticket before the next release. What do you think?

**Comment by acs** [comment]
I am not aware about 

https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/cfg_generator

Not sure what approach is more complete. I prefer to have it included in mordred to avoid small scripts that must be maintained.

**Comment by valeriocos** [comment]
The [cfg_generator](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/cfg_generator) is pretty old and doesn't seem to be used somewhere else. I've just pushed a PR to remove it: https://github.com/chaoss/grimoirelab-sirmordred/pull/185

**Comment by sanacl** [comment]
Can we close this ticket then @valeriocos ?
