### ISSUE TITLE
Sortinghat identities are not correctly synced with the enriched indexes

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#188]
The current implementation of Mordred does not get the identities data synchronized from SortingHat database to the enriched indexes. Given this is a behavior seen in production I started to read some code and I found the issues detailed below.

* The date used to query when the SH database was changed is calculated based on when Mordred is started. So if Mordred fails or is restarted, there is no way of knowing the data we have to sync:

   * This is how we get the latest modification time of the enriched index (basically we make it up): https://github.com/chaoss/grimoirelab-sirmordred/blob/38832a46498c54bdafe67ff93dfb4dbd5841e436/sirmordred/task_enrich.py#L64
   * That field is used here:
https://github.com/chaoss/grimoirelab-sirmordred/blob/38832a46498c54bdafe67ff93dfb4dbd5841e436/sirmordred/task_enrich.py#L198

* The date of the latest update of the enriched index is set before the update operation is executed, so if something goes wrong the next iteration of the loop will not try again:
   https://github.com/chaoss/grimoirelab-sirmordred/blob/38832a46498c54bdafe67ff93dfb4dbd5841e436/sirmordred/task_enrich.py#L201

**Comment by sanacl** [comment]
My proposal for solving this. The only way of getting this information synchronized is by adding information about the modification time of the identity to the enriched index. I guess that copying the same time value written in Sorting Hat and feeding a field in the enriched index ( for instance `sh_identity_updated_at`) would allow us to get that synced copy.

So, Mordred would query first the enriched index and with the max date would query the Sorting Hat database. If anything wrong happens, the only source of information needed to know what should be updated next will be available in the enriched index.

**Comment by sduenas** [comment]
This was already fixed in the latest release. Closing it.
