### ISSUE TITLE
Sortinghat variables 'autoprofile' and 'matching' should not be required

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-sirmordred#189]
The configuration variables `autoprofile` and `matching` can create a conflict when Hatstall is being used to modify the identities database. Currently when matching is equal to `[]` the sorting hat command `unify` is executed with `-m ''` which could produce unexpected results.

In order to avoid conflicts with modifications done via the UI (Hatstall), Mordred must allow to disable those automatic methods. So if these variables don't exist or they are assigned to an empty list, the `autoprofile` and `unify` sortinghat methods should not be executed.

**Comment by jjmerchante** [comment]
Currently, the methods are not executed if those variables are assigned to an empty list. The issue has been resolved.
