### ISSUE TITLE
Weird warning could be removed

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sirmordred#192]
When I launch SirMordred, I get a lot of messages like this:

```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```

Apparently, this is an inoffensive warning caused by some package importing a version of numpy which is not the version for which it was compiled. But it can be safely ignored. The fix is:

```python
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
```

While this is fixed in the imported packages, could we have this code in SirMordred?

More details in [this Stackoverflow Q/A](https://stackoverflow.com/a/40846742/2075265)

**Comment by sanacl** [comment]
I guess this ticket can be closed @jgbarah . Can u please confirm?

**Comment by jgbarah** [comment]
Yes. Thanks! Closing....
