### ISSUE TITLE
Error installing dependencies: "Python.h: No such file or Directory"

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#251]
This is not a real bug but a common issue seen when installing Mordred dependencies. If you don't have the proper packages you'll see this error:

`dulwich/_objects.c:21:10: fatal error: Python.h: No such file or Directory`

The solution is easy, make sure you have the python3 development package installed (the one matching your Python version). For debian this can be solved by executing:

`# apt-get install python3-dev`

This ticket will be closed as it was creating just for avoiding our community folks to lose time with this.

**Comment by jgbarah** [comment]
Thanks @sanacl! I'm fixing this in chaoss/grimoirelab-tutorial#50

I think we should open a ticket for this in chaoss/grimoirelab-perceval and chaoss/grimoirelab as well.

**Comment by JanisSharma** [comment]
On Ubuntu, I was running Python 3 and I had to install

sudo apt-get install python3-dev
If you want to use a version of Python that is not linked to python3, install the associated python3.x-dev package. For example:

sudo apt-get install python3.5-dev

Find All solutions [Here](https://icetutor.com/question/fatal-error-python-h-no-such-file-or-directory)

**Comment by valeriocos** [comment]
Thank you @JanisSharma for providing feedback!

Feel free to have a look at the [tutorial](https://github.com/chaoss/grimoirelab-tutorial) (maybe in the `basics` section) to see if what you found can fit there.

Thanks!
