### ISSUE TITLE
how to configure jenkins credentials

### ISSUE THREAD

**Issue by nitishvu** [chaoss/grimoirelab-sirmordred#287]
how to configure jenkins "username" and "password" in  sirmordered.conf

please help

**Comment by valeriocos** [comment]
Hi @nitishvu , jenkins doesn't support "username" and "password". You can configure it in the following way:
**setup.cfg**
```
[jenkins]
raw_index = jenkins_raw
enriched_index = jenkins_enriched
no-archive = true
```

**projects.json**
```
{
...
  "jenkins": ["https://build.opnfv.org/ci"]
...
}
```

**Comment by nitishvu** [comment]
Hi @valeriocos  thanks for you response.
I think we should have this feature, I would like to contribute.
as per my understanding we have  make changes in both sirmordred and Perceval.
please let me know your comments

**Comment by valeriocos** [comment]
It's could be a good idea to have this feature, what do you think @sduenas . 
@nitishvu , do you have an example of a jenkins that requires username and password?

**Comment by sduenas** [comment]
There's an issue open about this since a few months ago: https://github.com/chaoss/grimoirelab-perceval/issues/432

**Comment by valeriocos** [comment]
After almost 8 months of inactivity on that issue and corresponding PR, I guess @nitishvu you are more than welcome to give it new life. Thanks!

**Comment by nitishvu** [comment]
hi @valeriocos ,

sorry I didn't know that we can use it in below format. I am use the data collector now :)
    perceval jenkins http://username:password@jenkins.devops.com:8080/ 
thanks,
Nitish

**Comment by valeriocos** [comment]
Thank you for reporting the solution (I didn't know it either :)) @nitishvu . I guess the feature in Perceval can still be of interest if you want to go for it.

**Comment by nitishvu** [comment]
you are welcome @valeriocos, will start working on Perceval module. later we can try to include in sirmordred

**Comment by valeriocos** [comment]
Sure @nitishvu , no modification should be required in mordred since it passes all params excluding [a small subset](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task.py#L136) to Perceval

**Comment by sduenas** [comment]
This is now supported in Perceval (see chaoss/grimoirelab-perceval#432 ). Setting the parameters (user and API token) in Mordred will work.
