### ISSUE TITLE
Deprecated call to yaml.load

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sirmordred#288]
When launching `sirmordred` with any configuration, you see two warnings:

```
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
/usr/local/lib/python3.5/dist-packages/sirmordred/task_panels.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.panels_menu = yaml.load(f)
/usr/local/lib/python3.5/dist-packages/sirmordred/task_panels.py:437: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.panels_menu = yaml.load(f)
```

I think the fix is easy: just call yaml.load() with a `Loader` parameter.

I know this is not exactly a bug, since it produces the right output. But I'm labeling as bug because it is kindda confusing for the user, anyway...

**Comment by valeriocos** [comment]
The fix should be similar to the code in this PR: https://github.com/chaoss/grimoirelab-sortinghat/pull/200

@sumitskj this could be good for you for [micro-task 9](https://github.com/chaoss/grimoirelab/issues/182), what do you think ? :)

**Comment by sumitskj** [comment]
> The fix should be similar to the code in this PR: [chaoss/grimoirelab-sortinghat#200](https://github.com/chaoss/grimoirelab-sortinghat/pull/200)
> 
> @sumitskj this could be good for you for [micro-task 9](https://github.com/chaoss/grimoirelab/issues/182), what do you think ? :)

Sure, I will try to fix this

**Comment by valeriocos** [comment]
great! thank you @sumitskj

**Comment by sumitskj** [comment]
I have added the Loader param in yaml.load() #289 but it has failed to pass tests. Can you see this.

**Comment by valeriocos** [comment]
Thank you working on this issue @sumitskj .The tests fail due to a missing package. I'll make a local test and merge it

**Comment by valeriocos** [comment]
Merged, thank you @sumitskj
