### ISSUE TITLE
Debug messages still being showen when running micro.py without debug flag

### ISSUE THREAD

**Issue by arnonm-intel** [chaoss/grimoirelab-sirmordred#295]
It looks like a few of the modules have debug on by default, regardless of what logger is set to. examples are:
 urllib3.connectionpool - DEBUG] 
perceval.archive - DEBUG] 
 perceval.backends.core.jenkins - DEBUG]

**Comment by valeriocos** [comment]
Thank you @arnonm-intel for reporting this issue, we will have a look at it in the next days.
