### ISSUE TITLE
Issue connecting to secured Elasticsearch cluster

### ISSUE THREAD

**Issue by alangsto** [chaoss/grimoirelab-sirmordred#309]
I am using the grimoirelab/installed docker image, and trying to configure connections to a secured Elasticsearch cluster being hosted on AWS. I have mounted my own infra.cfg file containing relevant information about usernames/passwords/urls to the image, but when I try to run the container I get the error: 

`sirmordred.sirmordred - ERROR - Cannot connect to Elasticsearch: https://e69eb515c21ebbcaf026c5d04dc49f1a.us-east-1.aws.found.io:9243`

I have verified that I can connect to the cluster by logging in through the browser. 

Does Grimoirelabs support secured clusters, or does anyone know how to get around this issue?

**Comment by valeriocos** [comment]
Hi @alangsto, 
AFAIK we have an instance of GrimoireLab in AWS for one of our customers. Probably @sanacl and @zhquan can help you with this

**Comment by zhquan** [comment]
Hi @alangsto,
Maybe there is something wrong with your setup.cfg, could you share it?

**Comment by alangsto** [comment]
Hi @zhquan, this is the infra.cfg file that I had mentioned before. I took out any sensitive information, and replaced it with X's. 

`
[general]
# Directory for logs
logs_dir = /logs
# File with aliases definitions
aliases_file = /aliases.json
# File with menu defintions
menu_file = /menu.yaml

[projects]
projects_file = /projects.json

[es_collection]
# Elasticsearch for data collection (raw indexes)
url = https://e69eb515c21ebbcaf026c5d04dc49f1a.us-east-1.aws.found.io:9243
user = XXX
password = XXX

[es_enrichment]
# Elasticsearch for enriched data
url = https://e69eb515c21ebbcaf026c5d04dc49f1a.us-east-1.aws.found.io:9243
user = XXX
password = XXX

[sortinghat]
# Infrastructure for SortingHat (MariaDB/MySQL database)
host = er7lx9km02rjyf3n.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
user = XXX
password = XXX
database = XXX

# Use organizations file
load_orgs = true
orgs_file = /orgs.json

# Identities file in GrimoireLab format
#identities_file = [/identities.yaml]
#identities_format = grimoirelab

[panels]
# Kibitter / kibana entry point
kibiter_url = https://055db0b6a8c8e272e30fd08f5dae5fc9.us-east-1.aws.found.io:9243
`

**Comment by zhquan** [comment]
Hi @alangsto,

Could you try to set the `kibiter_url` in the section `panels` to the value `https://<user>:<password>@e69eb515c21ebbcaf026c5d04dc49f1a.us-east-1.aws.found.io:9243/_plugin/kibana` (by default AWS give you a kibana in `ES/_plugin/kibana`)? 

Please use the following format: `https://<user>:<password>@e69eb515c21ebbcaf026c5d04dc49f1a.us-east-1.aws.found.io:9243`

**Comment by alangsto** [comment]
Hi @zhquan,

I actually managed to fix this issue by downgrading my elasticsearch version from 7.1 to 6.1. 

Thanks for your help!
