### ISSUE TITLE
Kibiter is not displaying any data

### ISSUE THREAD

**Issue by electrocucaracha** [chaoss/grimoirelab-sirmordred#313]
Hey there, 

I have reviewed the documentation to make sure that the configuration files properly setup and double-checked that the arthur workers are fetching the information but the graphs are not populated in the dashboard, this is my [sirmordred config file](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/setup_mordred.ini)

```
[general]
short_name = Grimoire
update = true
debug = true
logs_dir = /var/log
menu_file = /sirmordred/conf/menu.yaml
aliases_file = /sirmordred/conf/aliases.json
# number of items per bulk request to Elasticsearch
bulk_size = 5000
# number of items to get from Elasticsearch when scrolling
scroll_size = 1000

[projects]
projects_file = /sirmordred/conf/projects.json

[es_collection]
arthur = true
url = http://elasticsearch:9200
arthur_url = http://arthurd:8080
redis_url = redis://redis/8

[es_enrichment]
url = http://elasticsearch:9200

[sortinghat]
host = mariadb
user = root
password = secret
database = sortinghat
affiliate = false
unaffiliated_group = Unknown
matching = ['github']
sleep_for = 3600
autoprofile = ['customer', 'git', 'github']

[phases]
collection = true
identities = false
enrichment = false
panels = true

[panels]
community = false
kibiter_url = http://kibiter:5601

[git]
raw_index = git
enriched_index = git
category = commit
```

And this is my [auto-generated projects.json](https://github.com/electrocucaracha/grimoirelab/blob/master/postinstall.sh#L101-L118) file

```
{
  "openstack": {
    "git": [
      "https://github.com/openstack/swift",
      "https://github.com/openstack/nova",
      "https://github.com/openstack/glance"
    ]
  }
}
```

Am I missing something? I'm bringing up the services with [docker-compose file](https://github.com/electrocucaracha/grimoirelab/blob/master/docker-compose.yml) and I have plans to migrate this to Kubernetes any help would be really appreciated.

**Comment by valeriocos** [comment]
Hi @electrocucaracha , sorry for the late reply. It could be great if you can share some logs. Find below a list of possible explanations for your issue.

Depending on the size of the repo, it may take some time to see the data in Kibana. Have you checked that the indexes in your elasticsearch are being populated?

The issue could be related to the names defined for the `raw_index` and `enriched_index` in the git section of the setup.cfg, they cannot be the same. Try with `openstack_git_raw` and `openstack_git_enriched`.

The issue can be related to the resources allocated to your ES. For instance, the `bulk_size` value seems pretty high (5000) and can stress your env. Maybe you can try with 1000 or less.

It could be that the repos listed in your projects.json have been already downloaded locally (maybe you launched the docker-compose several times and stopped it when the collection phase was being executed).  Due to the way the [Git backend](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py) works, you may get only the new commits between the initial collection and the next one. You can try to delete the repos (downloaded by default at this [path](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L336))  and start again the container.

**Comment by valeriocos** [comment]
I've just checked your docker-compose, I'm not sure about the settings for `elasticsearch`. Ports and resources are not declared. You may try with the following one
```
elasticsearch:
  restart: on-failure:5
  image: bitergia/elasticsearch:6.1.0
  command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
  ports:
    - 9200:9200
```

**Comment by electrocucaracha** [comment]
> Hi @electrocucaracha , sorry for the late reply. It could be great if you can share some logs. Find below a list of possible explanations for your issue.

Hola @valeriocos, I'll try to capture and share the most relevant logs of the execution. This is the log for [Elasticsearch](http://paste.openstack.org/show/753838/) and this is a [Kibiter's screenshot ](https://pasteboard.co/ImhvWnK.png)

> Depending on the size of the repo, it may take some time to see the data in Kibana. Have you checked that the indexes in your elasticsearch are being populated?

I noticed that Arthur workers created `git` index but I'm not sure how can I verify if the information is populated. AFAIK Arthur is properly configured but I could be wrong.

> The issue could be related to the names defined for the `raw_index` and `enriched_index` in the git section of the setup.cfg, they cannot be the same. Try with `openstack_git_raw` and `openstack_git_enriched`.

Gotcha, I'm going to rename them to avoid conflicts.

> The issue can be related to the resources allocated to your ES. For instance, the `bulk_size` value seems pretty high (5000) and can stress your env. Maybe you can try with 1000 or less.

> It could be that the repos listed in your projects.json have been already downloaded locally (maybe you launched the docker-compose several times and stopped it when the collection phase was being executed). Due to the way the [Git backend](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py) works, you may get only the new commits between the initial collection and the next one. You can try to delete the repos (downloaded by default at this [path](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/git.py#L336)) and start again the container.

If you want to try this project the only requirement is to have *vagrant* software installed. I've capture the vagrant's installation instructions in [this](https://github.com/electrocucaracha/krd/blob/master/setup.sh) bash script, the only thing to run is `./setup.sh -p libvirt` for installing vagrant + libvirt in your linux server. Once vagrant is installed you create an environment with `vagrant up` instruction which will provision a VM and install the dependencies.

**Comment by electrocucaracha** [comment]
> I've just checked your docker-compose, I'm not sure about the settings for `elasticsearch`. Ports and resources are not declared. You may try with the following one
> 
> ```
> elasticsearch:
>   restart: on-failure:5
>   image: bitergia/elasticsearch:6.1.0
>   command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
>   environment:
>     - ES_JAVA_OPTS=-Xms2g -Xmx2g
>   ports:
>     - 9200:9200
> ```

The configuration options were stored in the [elasticsearch.yml configuration file](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/elasticsearch.yml) and [mounted](https://github.com/electrocucaracha/grimoirelab/blob/master/docker-compose.yml#L38) as in the docker-compose file. AFAIK, it's not necessary to map the ports because they won't be consumed externally.

**Comment by valeriocos** [comment]
Hola @electrocucaracha , thank you for the info. The problem should be caused by:
```
elasticsearch_1  | [2019-07-03T15:03:21,972][DEBUG][o.e.a.b.TransportShardBulkAction] [.kibana][0] failed to execute bulk item (index) BulkShardRequest [[.kibana][0]] containing [index {[.kibana][doc][dashboar
d:Overview], source[n/a, actual length: [7.5kb], max length: 2kb]}]                                                                                                                                              

elasticsearch_1  | org.elasticsearch.index.mapper.StrictDynamicMappingException: mapping set to strict, dynamic introduction of [release_date] within [dashboard] is not allowed
``` 

In a nutshell, the `.kibana` stores the visualizations, if it isn't created, the visualizations won't appear.

To confirm that the data is there and it is just a problem of the .kibana, could you try to list the content of your ElasticSearch. You can achieve it by entering in the dev tools inside Kibiter and then execute:
- `GET _alias` to list the indexes in your ES
- `GET <name-of-the-index-(raw or enriched)>/_search` to see the content of the index (or `GET <name-of-the-index-(raw or enriched)>/_count` to know the number of docs in your index)

Find below a gif that recaps the steps:
![Peek 04-07-2019 17-01](https://user-images.githubusercontent.com/6515067/60676066-3ee87380-9e7e-11e9-9cb7-334c0ab48778.gif)

**Comment by electrocucaracha** [comment]
>     * GET _alias

@valeriocos It seems like the information is not populated properly even when the worker is finishing the task.

```
arthurw_10       | [2019-07-05 07:11:53,777 - perceval.backends.core.git - INFO] - Fetch process completed: 9437 commits fetched                                                                                 
arthurw_10       | [2019-07-05 07:11:53,777 - arthur.jobs - DEBUG] - Job #arthur-https://github.com/openstack/swift_git-cc63793f-acf6-4e7f-83d2-5b859a362800 (task: https://github.com/openstack/swift_git) compl
eted (git) - 9437 items (commit) fetched                                                                                                                                                                         
arthurw_10       | [2019-07-05 07:11:53,780 - rq.worker - INFO] - create: Job OK (arthur-https://github.com/openstack/swift_git-cc63793f-acf6-4e7f-83d2-5b859a362800)   
```

And the api is notified

```
[2019-07-05 07:11:53,791 - root - DEBUG] - Job #arthur-https://github.com/openstack/swift_git-cc63793f-acf6-4e7f-83d2-5b859a362800 completed                                                                    
[2019-07-05 07:11:53,791 - root - DEBUG] - Calling handler for job #arthur-https://github.com/openstack/swift_git-cc63793f-acf6-4e7f-83d2-5b859a362800                                                           [2019-07-05 07:11:53,792 - root - DEBUG] - Job #arthur-https://github.com/openstack/swift_git-324c2441-a61d-42d6-9667-24aed2af8e79 (task: https://github.com/openstack/swift_git) scheduled on update (wait: 60
```

`GET _alias`
```
{
  "git-raw": {
    "aliases": {}
  },
  ".kibana": {
    "aliases": {}
  }
}
```
`GET git-raw/_search`
```
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```
 
BTW, I submitted the [PR](https://github.com/chaoss/grimoirelab-perceval/pull/548) for adding proxy support to the `git clone` perceval task

**Comment by electrocucaracha** [comment]
I left the service running for few hours and now it's displaying at least one record

```
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "git-raw",
        "_type": "items",
        "_id": "d26ff9744b9e97f92a91fff56fbf54c9cd467aa6",
        "_score": 1,
        "_source": {
          "backend_name": "Git",
          "updated_on": 1562164116,
          "metadata__updated_on": "2019-07-03T14:28:36+00:00",
          "classified_fields_filtered": null,
          "data": {
            "commit": "345f577ff191ee01c3cb4626805338028815c2b4",
            "AuthorDate": "Wed Jul 3 07:28:14 2019 -0700",
            "refs": [
              "HEAD -> refs/heads/master"
            ],
            "Commit": "Tim Burke <tim.burke@gmail.com>",
            "CommitDate": "Wed Jul 3 07:28:36 2019 -0700",
            "message": """
s3token: fix conf option name

Related-Change: Ica740c28b47aa3f3b38dbfed4a7f5662ec46c2c4
Change-Id: I71f411a2e99fa8259b86f11ed29d1b816ff469cb
""",
            "Author": "Tim Burke <tim.burke@gmail.com>",
            "files": [
              {
                "file": "etc/proxy-server.conf-sample",
                "modes": [
                  "100644",
                  "100644"
                ],
                "indexes": [
                  "e0cb65717...",
                  "37c1c7cf7..."
                ],
                "added": "1",
                "removed": "1",
                "action": "M"
              }
            ],
            "parents": [
              "dc84c69c652d899bf6b8177fa352cf980ae5ff8a"
            ]
          },
          "arthur_version": "0.1.15",
          "backend_version": "0.11.1",
          "timestamp": 1562342318.495184,
          "category": "commit",
          "origin": "https://github.com/openstack/swift",
          "job_id": "arthur-https://github.com/openstack/swift_git-fd3954a2-8273-424a-aad5-4bfeeaf12a75",
          "tag": "https://github.com/openstack/swift_git",
          "uuid": "d26ff9744b9e97f92a91fff56fbf54c9cd467aa6",
          "perceval_version": "0.12.17",
          "metadata__timestamp": "2019-07-05T15:58:38.495184+00:00"
        }
      }
    ]
  }
}
```
But the graphs are still in blank

**Comment by electrocucaracha** [comment]
It seems like the `from_date` back-end value is not parsed properly. I modified the configuration of the git back-end to this:
```
[git]
raw_index = git-raw
enriched_index = git_enriched
category = commit
from_date = 2017-01-01
```
It seems like *sirmordred* is capable to parse that information and send it to *arthurd* in POST request:
```
2019-07-05 20:38:48,321 - urllib3.connectionpool - DEBUG - http://elasticsearch:9200 "POST /git-raw/_search HTTP/1.1" 200 150
2019-07-05 20:38:48,322 - sirmordred.task_collection - DEBUG - JSON config for arthur {
 "tasks": [
  {
   "scheduler": {
    "delay": 60
   },
   "backend_args": {
    "tag": "https://github.com/openstack/swift_git",
    "uri": "https://github.com/openstack/swift",
    "gitpath": "/tmp/https://github.com/openstack/swift",
    "category": "commit",
    "from_date": "2017-01-01",
    "url": "https://github.com/openstack/swift"
   },
   "category": "commit",
   "task_id": "https://github.com/openstack/swift_git",
   "archive": {},
   "backend": "git"
  }
 ]
}
```
But the *arthur worker* is not getting that information from redis
```
arthurw_3        | [2019-07-05 20:43:06,489 - rq.worker - INFO] - update: arthur.jobs.execute_perceval_job(archive_args=None, backend='git', backend_args={'gitpath': '/tmp/https://github.com/openstack/swift', 
'uri': 'https://github.com/openstack/swift', 'category': 'commit', 'from_date': datetime.datetime(2019, 7, 3, 14, 28, 36, tzinfo=tzutc()), 'tag': 'https://github.com/openstack/swift_git', 'url': 'https://githu
b.com/openstack/swift'}, category='commit', max_retries=3, qitems='items', task_id='https://github.com/openstack/swift_git') (arthur-https://github.com/openstack/swift_git-a3aed706-524f-4ff9-8111-7e4102e8e75d)
```

**Comment by electrocucaracha** [comment]
Apparently it requires quotes to parse the date time. I have modified the [configuration file](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/setup_mordred.ini#L50)

**Comment by valeriocos** [comment]
Hi @electrocucaracha, thank you for keeping investigating on this issue. @sanacl @jgbarah feel free to jump in the conversation

**Comment by sanacl** [comment]
Hi @electrocucaracha ,
I've been trying to figure out what is your current setup.cfg. According to what I saw:
* you are using Arthur. This is not recommended at all. Integration is not reliable. Please comment all lines related to `arthur`
* git indexes have the same name  under the section `[git]`. Enriched and raw indexes must have different names.

Can u apply those changes and share with us not the aliases but the names of the indexes created in your cluster?

**Comment by electrocucaracha** [comment]
Hey @sanacl,
The reason that I prefer Arthur is because it can be easily used by k8s I have plans to migrate this `docker-compose` solution to `kubernetes`. Regarding the index name I have changed them in this [commit](https://github.com/electrocucaracha/grimoirelab/commit/5b23e2638db6c3ddef008a8aad1d3f4456cb596f). I'm going to try but let me see if I can get an environment outside of our corporate proxy or resolve all the issues.

**Comment by valeriocos** [comment]
Hi @electrocucaracha , how is it going with this issue?

**Comment by electrocucaracha** [comment]
Well, maybe the last thing that I need to verify if the [json panels](https://github.com/electrocucaracha/grimoirelab/tree/master/sigils) that I'm using are not the right ones but other than that everything looks good. @valeriocos did you try to deploy the services using my `vagrant` method?

**Comment by valeriocos** [comment]
thank you for the quick reply @electrocucaracha , no I haven't tried so far. I'll try

**Comment by valeriocos** [comment]
@electrocucaracha sorry for the late reply.  I'm following the instructions at https://github.com/chaoss/grimoirelab-sirmordred/issues/313#issuecomment-508202190, however when doing `vagrant up` I got an error (see below).

```
slimbook@slimbook-KATANA:~$ vagrant -v
Vagrant 2.2.5
slimbook@slimbook-KATANA:~$ vagrant up
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

I also try to execute a raw collection using arthur and everything worked fine. I was using the docker-compose below and had arthur server and worker with the following conf:

**arthurd**
```
-g -d redis://localhost/8 --log-path /tmp/logs/arthurd --no-archive --no-daemon
```

**arthurw**
```
-g -d redis://localhost/8
```

**docker-compose**
```
elasticsearch:
  restart: on-failure:5
  image: bitergia/elasticsearch:6.1.0-secured
  command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
  ports:
    - 9200:9200

kibiter:
  restart: on-failure:5
  image: bitergia/kibiter:secured-v6.1.4-2
  environment:
    - PROJECT_NAME=Development
    - NODE_OPTIONS=--max-old-space-size=1000
    - ELASTICSEARCH_URL=https://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - 5601:5601
```

**Comment by electrocucaracha** [comment]
> @electrocucaracha sorry for the late reply. I'm following the instructions at [#313 (comment)](https://github.com/chaoss/grimoirelab-sirmordred/issues/313#issuecomment-508202190), however when doing `vagrant up` I got an error (see below).
> 
> ```
> slimbook@slimbook-KATANA:~$ vagrant -v
> Vagrant 2.2.5
> slimbook@slimbook-KATANA:~$ vagrant up
> A Vagrant environment or target machine is required to run this
> command. Run `vagrant init` to create a new Vagrant environment. Or,
> get an ID of a target machine from `vagrant global-status` to run
> this command on. A final option is to change to a directory with a
> Vagrantfile and to try again.
> ```

The error below is caused because you didn't clone the repository and execute the `vagrant up` command from that folder

> 
> I also try to execute a raw collection using arthur and everything worked fine. I was using the docker-compose below and had arthur server and worker with the following conf:
> 
> **arthurd**
> 
> ```
> -g -d redis://localhost/8 --log-path /tmp/logs/arthurd --no-archive --no-daemon
> ```
> 
> **arthurw**
> 
> ```
> -g -d redis://localhost/8
> ```
> 
> **docker-compose**
> 
> ```
> elasticsearch:
>   restart: on-failure:5
>   image: bitergia/elasticsearch:6.1.0-secured
>   command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
>   environment:
>     - ES_JAVA_OPTS=-Xms2g -Xmx2g
>   ports:
>     - 9200:9200
> 
> kibiter:
>   restart: on-failure:5
>   image: bitergia/kibiter:secured-v6.1.4-2
>   environment:
>     - PROJECT_NAME=Development
>     - NODE_OPTIONS=--max-old-space-size=1000
>     - ELASTICSEARCH_URL=https://elasticsearch:9200
>   links:
>     - elasticsearch
>   ports:
>     - 5601:5601
> ```

I tried to use those values in my [docker-compose.yml file](https://github.com/electrocucaracha/grimoirelab/blob/master/docker-compose.yml) but the `arthurd` container couldn't connect with `elasticsearch` service and `kibiter` web page wasn't loading properly. 

The current values of the *docker-compose.yml* file are making workers collect and report data to *arthurd* service and *elasticsearch* seems to receive the information:

```
GET git-raw/_count
{
  "count": 6374,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  }
}
```
So maybe there is misconfiguration of the *sigils* json panels that I'm using in the [menu.yml file](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/menu.yaml)

**Comment by valeriocos** [comment]
Do you have/see enriched indexes in your ElasticSearch? It could be just a matter of giving more resources to Elasticsearch (`ES_JAVA_OPTS=-Xms2g -Xmx2g`)?

I'm not sure about the misconfiguration of the sigils panels, I checked your docker-compose/menu.yml and seem OK. Panels are loaded by the [task panels](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_panels.py) using [read_panel_file](https://github.com/chaoss/grimoirelab-kidash/blob/master/kidash/kidash.py#L660) in kidash (try to have a look at the latter, maybe it can help you). Note that kidash can be used as stand-alone tool to upload the dashboards (in the worst case, this might be a temporary solution).

**Comment by electrocucaracha** [comment]
I have disable *identities* and *enrichment* phases from the [sirmordred configuration file ](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/setup_mordred.ini#L38-L39) because otherwise the enrichment process never finishes.

```
2019-07-23 19:31:46,475 - urllib3.connectionpool - DEBUG - http://elasticsearch:9200 "GET /git_enriched HTTP/1.1" 404 160
2019-07-23 19:31:47,005 - urllib3.connectionpool - DEBUG - http://elasticsearch:9200 "PUT /git_enriched HTTP/1.1" 200 78
2019-07-23 19:31:47,006 - grimoire_elk.elastic - INFO - Created index http://elasticsearch:9200/git_enriched
2019-07-23 19:31:47,006 - grimoire_elk.elastic - DEBUG - http://elasticsearch:9200/git_enriched/_search 
        { "size": 0, "query": {"bool": {"filter": []}},  
            "aggs": {
                "1": {
                  "max": {
                    "field": "metadata__timestamp"
                  }
                }
            }
        
        } 
2019-07-23 19:31:47,087 - urllib3.connectionpool - DEBUG - http://elasticsearch:9200 "POST /git_enriched/_search HTTP/1.1" 200 150
2019-07-23 19:31:47,088 - sirmordred.task_enrich - INFO - [git] enrichment starts for https://github.com/openstack/glance
2019-07-23 20:31:36,249 - sirmordred.task_manager - INFO - [thread:139627309352704][Global tasks] Tasks started: <sirmordred.task_projects.TaskProjects object at 0x7efd7b40f6d8>
2019-07-23 20:31:36,249 - sirmordred.task_projects - INFO - Reading projects data from  /sirmordred/conf/projects.json 
2019-07-23 20:31:36,250 - sirmordred.task_projects - DEBUG - Update project diff []
2019-07-23 20:31:36,250 - sirmordred.task_manager - INFO - [thread:139627309352704][Global tasks] Tasks finished: <sirmordred.task_projects.TaskProjects object at 0x7efd7b40f6d8>
2019-07-23 20:31:36,250 - sirmordred.task_manager - INFO - [thread:139627309352704][Global tasks] sleeping for 3600 seconds 
```
What I have seen is that using that configuration populates data with fields that are not expected by the visualizations like `author_name` instead of `data.Author` or `hash` instead of `_id`, I guess that those fields are created by SortingHat which in my case is disabled so I'll need to create custom visualizations.

**Comment by valeriocos** [comment]
ok, it is strange that the enrichment phase never ends, however thank you for sharing this info. If you think it can be useful, we can talk on the IRC channel #grimoirelab (freenode) so you can explain me how to replicate your env (I didn't get your comment `The error below is caused because you didn't clone the repository and execute the vagrant up command from that folder`).

Visualizations are tailored only to enriched indexes, so if you disable the enrichment phase you have to create your own dashboards.
When you set the from-date in the setup.cfg, the incremental fetch doesn't work. It means that for every collection, the raw data will be fetched from that date.

**Comment by sanacl** [comment]
@electrocucaracha if you don't need identities data why don't create the visualizations on top of the raw indexes?

**Comment by electrocucaracha** [comment]
@sanacl that's right, I didn't know that *sigils* panels are based on *sortinghat* output. I defined a custom [git.json panel](https://github.com/electrocucaracha/grimoirelab/blob/master/conf/git.json) which I used for capture this [screenshot](https://github.com/electrocucaracha/grimoirelab/blob/master/docs/src/img/kibiter_screenshot.png).

@valeriocos I was connected to IRC but I could find your nick there. I tried to document better the way to deploy this project in this [document](https://github.com/electrocucaracha/grimoirelab/blob/master/docs/src/deployment.rst). If you have `Vagrant` and `VirtualBox` or `Libvirt` installed these the only instructions required for provisioning a Virtual Machine:

    $ git clone --recurse-submodules --depth 1 http://github.com/electrocucaracha/grimoirelab
    $ cd grimoirelab
    $ vagrant up

Anyway, I'm going to try to create a Chart for deploying this in Kubernetes through Helm. Hopefully I can share something soon. Thanks for the support and addressing my questions.

**Comment by valeriocos** [comment]
Thank you @electrocucaracha for sharing the document, I'll check it out. Feel free to drop an email to valcos@bitergia.com if/when you want to talk on IRC about this.

**Comment by electrocucaracha** [comment]
> ok, it is strange that the enrichment phase never ends, however thank you for sharing this info. If you think it can be useful, we can talk on the IRC channel #grimoirelab (freenode) so you can explain me how to replicate your env (I didn't get your comment `The error below is caused because you didn't clone the repository and execute the vagrant up command from that folder`).

@valeriocos I was trying to enable *enrichment* phase and I noticed that [get_connector_from_name elk's method](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/utils.py#L155-L166) is consumed differently from `TaskRawDataCollection`, `TaskRawDataArthurCollection` and `TaskEnrich` sirmordred's classes.

_TaskRawDataCollection_ class is using [feed_backend elk's method](https://github.com/chaoss/grimoirelab-sirmordred/blob/7457867fbd2e2bc9ada25c4fa913fa4bcd0f9128/sirmordred/task_collection.py#L130-L133) which uses the [third argument](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L120) to instantiate a Backend class.  _TaskEnrich_ does a similar thing using the [enrich_backend elk's method](https://github.com/chaoss/grimoirelab-sirmordred/blob/7457867fbd2e2bc9ada25c4fa913fa4bcd0f9128/sirmordred/task_enrich.py#L174-L204). But the _TaskRawDataArthurCollection_ class defines the `collect_arthur_items` nested function which uses the [first](https://github.com/chaoss/grimoirelab-sirmordred/blob/7457867fbd2e2bc9ada25c4fa913fa4bcd0f9128/sirmordred/task_collection.py#L384) argument.

I just wonder if this could be the reason that my collecting tasks only work when I enable **Arthur**.

**Comment by valeriocos** [comment]
I'm not sure that this is the reason.

Arthur schedules Perceval jobs and makes the items available through a Redis queue, thus it's not needed to instantiate the Perceval backends (since this logic is already embedded in Arthur). On the other hand, when using the TaskRawDataCollection, the backend is instantiated and the items fetched by Morded/ELK.

I'm off until Wed, but I can have a closer look when back.

**Comment by valeriocos** [comment]
Sorry for the late reply @electrocucaracha . It's difficult to test it since Arthur is not used in our prd envs. I would suggest you to disable arthur and use the `TaskRawDataCollection`.

We are working on evolving the platform to use Arthur as a scheduler. Sorry for the inconvenience
