### ISSUE TITLE
Allow to archive repositories

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sirmordred#329]
Sometimes we want to keep the history, activity and metrics of repositories that don't exist anymore.

With the current behaviour, when a repository does not exist, Mordred raises accessing errors. If these repositories are removed from the `projects.json` file, the repositories will be removed from the indexes when they are reindexed.

To avoid this behaviour, we should expand the `projects.json` schema to include a section with `archived` repositories. These projects will be ignored during the task collection phase but we'll be used during the enrichment one.

**Comment by GeorgLink** [comment]
+1
Excellent idea.

**Comment by valeriocos** [comment]
fixed with #337
