### ISSUE TITLE
Reload identities and organizations files when updated

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sirmordred#332]
SirMordred loads SortingHat files in an infinite loop even when it's not needed because there weren't changes. It should reload the list live and only when it changes.

**Comment by valeriocos** [comment]
Fixed by https://github.com/chaoss/grimoirelab-sirmordred/pull/336

**Comment by sduenas** [comment]
I would close it now because is already supported. Isn't it?
