### ISSUE TITLE
Affiliations wrongly updated before unify is finished

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#360]
One of our production instances with the parameter `reset_on_load` set to _true_ shown a strange behavior and suddenly all the affiliation entries were set to Unknown. This is not the expected behavior. When identities got reset, they should be unified before any enrichment+refresh phase is executed. Between the load of the identities file and the end of the unify command neither enrichment or refresh should be executed.

Have a look at the screenshot below from the production instance, where our customer complained about this issue.

![BUG-FINOS-UNKNOWN-RESET](https://user-images.githubusercontent.com/326719/67243518-059d3900-f458-11e9-8112-13f4141ff150.png)

This behavior was detected with Mordred 0.2.31

**Comment by valeriocos** [comment]
Thank you for reporting the bug @sanacl , due to new organization of this week (Tue-Thu everybody working on the new platform) I'm not sure we can process it before Friday.

**Comment by valeriocos** [comment]
Thank you @sanacl for reporting this issue. I won't be able to address it before Friday

**Comment by valeriocos** [comment]
Please @sanacl , review the PR (https://github.com/chaoss/grimoirelab-sirmordred/pull/364), thanks!

**Comment by valeriocos** [comment]
> One of our production instances with the parameter reset_on_load set to true shown a strange behavior and suddenly all the affiliation entries were set to Unknown.

I wasn't able to replicate this behaviour, it may be due to some latency in refreshing the enriched items.

> When identities got reset, they should be unified before any enrichment+refresh phase is executed. Between the load of the identities file and the end of the unify command neither enrichment or refresh should be executed.

Fixed with https://github.com/chaoss/grimoirelab-sirmordred/pull/364
