### ISSUE TITLE
[question] code-license and code-complexity analysis

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-sirmordred#365]
Hi! After a couple of weeks of doing 'other stuff', I'm picking GrimoireLab up again. Still very excited about it :) I would like to experiment with the Graal colic and cocom analysis. Is there an all-in-one docker / docker-compose option to run GrimoireLab with those available? The current `grimoirelab/full` doesn't have the `cloc` and `nomossa` binaries (and probably neither `scancode`, but didn't check).

**Comment by valeriocos** [comment]
Thank you @svdo for your interested! 

The docker image should be out in the next days, `cloc` and possibly the other binaries could be added to the all-in-one docker. WDYT @jgbarah? How difficult is to include these binaries? I can help you with that, thanks.

**Comment by svdo** [comment]
That would be awesome!

**Comment by jgbarah** [comment]
The new Docker images are out there. Graal is in it, but unfortunately not the binaries to run it. They could be installed, though, in the running container. @valeriocos I can work with you to include them in the grimoirelab/full image, and we release a new version.

**Comment by sanacl** [comment]
Question out of curiosity, what we need here is just a couple of pip packages installed in the docker container, am I right?

**Comment by jgbarah** [comment]
Yes. Some are Python packages, those are easy. Some are (if I recall well) packages in Debian. Those are easy too. But then we had some compiled from source. That's a bit more difficult...

**Comment by valeriocos** [comment]
Related to https://github.com/chaoss/grimoirelab/pull/230

**Comment by svdo** [comment]
I'm testing with my self-built `grimoirelab/full-3p` image as per https://github.com/chaoss/grimoirelab/pull/230. Closing.
