### ISSUE TITLE
Decommission support for Eclipse projects

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#367]
Long ago we included support to the format used by the Eclipse foundation. This is no longer used and the code should be decommissioned in my opinion.

Currently there is an option like this: `load_eclipse (bool: False): Load the projects from Eclipse` under `[projects]`.

What do u think folks?

**Comment by valeriocos** [comment]
+1

**Comment by sanacl** [comment]
I've checked both the code and functionality. LGTM
