### ISSUE TITLE
Decommission log rotation

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#368]
I do think sirmordred should not care about the log rotation. This is something that should be managed by the OS instead, as happens with other services such as apache or nginx.

Thus, I would decommission the following options and code associated:
```
[general]
    ..
    log_backup_count (int: 5): Number of rotate logs files to preserve
    log_handler (str: file): use rotate for rotating the logs automatically
    log_max_bytes (int: 104857600): Max number of bytes per log file
```

**Comment by valeriocos** [comment]
I tend to agree to this proposal, some questions below
- how logs are rotated currently (or is this code used in prd)?
- in your opinion, how many hours are needed to pass this responsability to the OS?

**Comment by sanacl** [comment]
> I tend to agree to this proposal, some questions below
> 
>     * how logs are rotated currently (or is this code used in prd)?
Code is not used in Bitergia. Our systems rotate the logs using the `logrotate` daemon (something typical in GNU/Linux systems)

> 
>     * in your opinion, how many hours are needed to pass this responsability to the OS?
Setting up logrotate for this is a 5-minute task. Example of configuration [here](https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04#setting-up-an-example-config)

**Comment by valeriocos** [comment]
thanks for the clarification, +1 then! We can schedule this task and the other ones for next week

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-sirmordred/pull/375
