### ISSUE TITLE
Some issues after moving droplet to new IP - no data sources updating, 500 errors

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab-sirmordred#372]
Hi folks,

I had to make a snapshot (after powering down) of our Droplet running the analytics-demo based docker instance in order to move under a team account.

I took the backup, spun up the new droplet, and all seemed to be great.

Unfortunately a few issues arose:
- Data sources aren't being updated
- Hatstall is giving 500 errors (I raised as a separate issue [here](https://github.com/chaoss/grimoirelab-hatstall/issues/90)).

Any ideas?

Docker compose ran without any errors (aside from the documented elasticsearch one which was resolved and then all was well) and the dashboard itself seems to be running OK.

**Comment by valeriocos** [comment]
Thank you @RCheesley for reporting this issue. Let's centralize the discussion on the issue https://github.com/chaoss/grimoirelab-hatstall/issues/90
