### ISSUE TITLE
Remove docker files from master branch

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#376]
Every time I start working with Mordred containers (it is not something I usually do) I have the same issue, I copy the content of the `/docker` folder from master and start modifying it. This is wrong because that code is deprecated. The code our folks should use is the one used by the latest release, which is in a branch that it is not merged to master.

In order to avoid our community members having the same pain in the neck my proposal is to remove the `/docker` folder from master branch.

**Comment by valeriocos** [comment]
please @jgbarah share your thoughts, thanks

**Comment by sanacl** [comment]
@valeriocos I think @jgbarah won't provide a lot of feedback. He is not using the Docker files in this repo but the ones at chaoss/grimoirelab.

**Comment by sduenas** [comment]
I think we should remove it and use the docker file from the latest release branch. Then, we'll create releases using tags and not branches.

**Comment by GeorgLink** [comment]
I support using tags for releases and having only one place for docker image(s).

**Comment by sanacl** [comment]
> I think we should remove it and use the docker file from  the latest release branch. Then, we'll create releases using tags and  not branches.

I would love to use tags instead of branches :)

**Comment by valeriocos** [comment]
@sanacl @sduenas should we remove the docker folder from the other repos too (perceval, ELK, etc.)? I see that they were modified long time ago.

**Comment by sanacl** [comment]
> @sanacl @sduenas should we remove the docker folder from the other repos too (perceval, ELK, etc.)? I see that they were modified long time ago.

I have no idea about containers for the rest of the tools. My guess is that they are quite old and no one is using that code either.

So as @sduenas said, let's remove the docker files. When we change the way of creating the container to use tags instead branches we can place updated files at `/docker` in master branch.

**Comment by sduenas** [comment]
> @sanacl @sduenas should we remove the docker folder from the other repos too (perceval, ELK, etc.)? I see that they were modified long time ago.

Not yet. As there's no alternative, we should keep them until we have one.

**Comment by valeriocos** [comment]
The latest release now uses the master branch, thus easing the life of devs working on changes in the mordred container. In the next release we will try to use tags

**Comment by valeriocos** [comment]
@sanacl can we close this issue? Now that the release workflow has changed and we use the docker folder in the master branch, it seems that this issue is invalid (or IT should be renamed). WDYT?

**Comment by valeriocos** [comment]
@sanacl I close this issue, feel free to reopen it if needed, thanks

**Comment by valeriocos** [comment]
The release 0.2.39 has been generated using tags. Feel free to have a look at https://github.com/chaoss/grimoirelab-sirmordred/tree/0.2.39
