### ISSUE TITLE
Unhealthy containers keep being unhealthy after a restart

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#401]
There is an error in the latest healthcheck for Mordred. The error makes impossible to remove the state "unhealthy" for containers which were marked as unhealthy before being rebooted. This happens because the cache file is not removed after the restart.

It is needed to add the line below:
`rm -f /tmp/.mordred_healthcheck`

This was part of a previous PR applied to master https://github.com/chaoss/grimoirelab-sirmordred/pull/379/files#diff-9150f1814f9739ce40b72176b36e9ddfR19

**Comment by valeriocos** [comment]
The new release is out, let's see if the error is gone. FYI, for this release, the branch https://github.com/chaoss/grimoirelab-sirmordred/tree/grimoirelab-0.2.38 was created from master (and not from https://github.com/chaoss/grimoirelab-sirmordred/tree/grimoirelab-0.2.37)

**Comment by sanacl** [comment]
LGTM @valeriocos
