### ISSUE TITLE
Enhancing the terminal logging

### ISSUE THREAD

**Issue by abhiandthetruth** [chaoss/grimoirelab-sirmordred#423]
The current terminal logging is monochrome and hence the user cannot differentiate between errors or successful completions of processes. Since this is the only real-time feedback mechanism to users, it would be effective or more user-friendly if we could differentiate those using colors at the least. Like all the error logs be red, process starts white, yellow for warnings and successful completions green. We can also highlight key terms for better readability. WDYT?

**Comment by valeriocos** [comment]
Hi @abhiandthetruth , thanks for sharing this idea, which look interesting. How do you plan to implement it?

**Comment by abhiandthetruth** [comment]
Thanks for your interest in this idea @valeriocos. Before starting to work on this, I iust wanted to know whether the idea gains interest, so haven't worked on it yet. I will start working on it right now and update you with the implementation. First priciple is to implement the idea without increasing the length of requirements.txt by much :).
