### ISSUE TITLE
Issue regarding the back-links

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-sirmordred#433]
I have observed a very small issue regarding the backlinks in the README.md, which was added in the recent PRs #430 #428.

The difference between 1 and 2 is very small (just a `-` in the end), but then when you click on 2, it won't go to the intended location.
1. https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#setting-up-a-pycharm-dev-environment-
2. https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#setting-up-a-pycharm-dev-environment

The feature of the backlinks is really helpful. The issue here is if some link is already shared in the past, this new change will kinda break the link.

**Comment by vchrombie** [comment]
I want to raise this, just to bring it to our knowledge.

I think we have two ways to proceed further.
1. Make a note of this change and make sure we put correct links from the hereafter and ignore the previously shared links (replacing all those shared links now, is almost an impossible job).
2. Revert the change so that everything comes to the same place.

**Comment by abhiandthetruth** [comment]
It's due to the added arrow characters, the same goes to the separated getting started section, now you cannot use #getting-started anymore. If we make changes they will lead to inconsistencies in the past documentation, it is inevitable, but I don't think reverting back is the correct option. We need to note this and use the corresponding links from now so that we can move forward developing new things. Ofcourse I may be biased since I was the one who created the concept but this is my opinion. WDYT @valeriocos ?

**Comment by imnitishng** [comment]
The README has gone through a complete haul over and looks more organised now, I think we should keep things as they are and fix any broken links as we encounter them.

**Comment by valeriocos** [comment]
Thank you for raising this point @vchrombie !

> Make a note of this change and make sure we put correct links from the hereafter and ignore the previously shared links (replacing all those shared links now, is almost an impossible job).

+1

Please @vchrombie @abhiandthetruth @imnitishng can you fix the links? Thanks

**Comment by valeriocos** [comment]
Hi @vchrombie @abhiandthetruth @imnitishng please let me know if you are working on it, or how you prefer to proceed.

Thanks :)

**Comment by abhiandthetruth** [comment]
I personally haven't started working on it. I think the best way will be finding all occurrences of the readme and replacing them with new one with an advanced text editor like vscode. Guess I'll get started :)

**Comment by abhiandthetruth** [comment]
Done @valeriocos in the all repos excluding [GrimoireLab](https://github.com/chaoss/grimoirelab). in total not many references were there. I think I covered all of the code and documentation( can't change the references in comments of-course) but there is always a possibility of mistake. And if everyone agrees that all of the links are fixed we may go ahead and close this issue :)

**Comment by valeriocos** [comment]
Thank you @abhiandthetruth

**Comment by vchrombie** [comment]
I think this can be closed now. :thinking:

**Comment by valeriocos** [comment]
sure! thanks for the suggestion @vchrombie
