### ISSUE TITLE
[doc] Improve the How to section

### ISSUE THREAD

**Issue by animeshk08** [chaoss/grimoirelab-sirmordred#439]
I have opened this issue to discuss the ways to improve the [How To](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to-) Section in the Getting Started Docs. 

As discussed [here](https://github.com/chaoss/grimoirelab-sirmordred/pull/428) a new How to section has been created in the Getting Started doc. However, it needs some improvements. We can include more visualizations or other subsections which can act as small tutorials to beginners.

**Comment by animeshk08** [comment]
Hi, @abhiandthetruth @vchrombie @ria18405 @imnitishng please provide any suggestions. Also, feel free to take-up subsections and submit a PR :)

Please tag anyone else who would be in interested in doing this :)

**Comment by abhiandthetruth** [comment]
Well done @animeshk08, the how to section is really well written. I will definitely provide suggestion if I find any :).

**Comment by valeriocos** [comment]
Thank you @animeshk08 ! I would suggest to keep adding things to the How to section, possible q&a could be:
- What is an index pattern and how to create it
- What is an index
- How to login to Kibiter
- How to inspect the quey created by a visualization
- How to create a dashboard
- How to edit a dashboard
- How to query elasticsearch from Kibiter (basically how to use the dev tools)
- How to apply filters
- How to check that the data is up to date (basically the data status dashboard)
- How to share a dashboard (basically how to create a short link)
- How to create a visualization
- How to edit a visualization
- How to edit the name of a visualization

Part of these q&a are already available at https://gitlab.com/Bitergia/c/FAQ/-/blob/master/how-to-dashboard/README.md. You can rely on it to answer these questions.

Please share your thoughts, thanks :)

**Comment by animeshk08** [comment]
Hi @valeriocos. Thank you so much for the reference. The Q&As you shared are valid and important. I will get a PR ready for a few of them :)

**Comment by valeriocos** [comment]
The `How to` section has been improved. Further improvements can be targeted by specific issues.
