### ISSUE TITLE
[tests] Investigate why CI tests fail

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-sirmordred#461]
The CI tests for the commit https://github.com/chaoss/grimoirelab-sirmordred/commit/ec6285e5f3550550e20bca08831f176809aeecbf failed (see details [here](https://travis-ci.org/github/chaoss/grimoirelab-sirmordred/jobs/679109056)), however the errors don't appear when executing the tests locally.

A possible explanation is that Travis is caching the data for a build.

**Comment by valeriocos** [comment]
The reason is that the ELK version installed in travis isn't the latest one (0.72.0), but the 0.63.0 (https://travis-ci.org/github/chaoss/grimoirelab-sirmordred/jobs/685610692#L411)

**Comment by vchrombie** [comment]
Sorry for the delay on this issue.

We have ported the CI service from Travis CI to GitHub Actions and currently, everything is working fine.
https://github.com/chaoss/grimoirelab-sirmordred/blob/master/.github/workflows/ci.yml

Closing it.
