### ISSUE TITLE
Facing issue with index in the  kibana dashboard and everything is blank in the dashboard

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab-sirmordred#483]
Hi all,

I am trying to open kibana dashboard at localhost:5601 and using the below setup.cfg file.
But due to this setup file , no index is created in the kibana dashboard and it shows the below image:

https://user-images.githubusercontent.com/63613092/88697364-c1387b00-d104-11ea-8026-d0527bc6871e.png

And it is asking to create index >
https://user-images.githubusercontent.com/63613092/88697485-ecbb6580-d104-11ea-86b2-926363a0bffc.png

Using below setup.cfg file:

```
[general]
short_name = Grimoirelab
update = true
min_update_delay = 60
debug = false
logs_dir = /tmp
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
github-repos = true


[phases]
collection = true
identities = true
enrichment = true
panels = true


[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
category = commit
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github]
api-token = xxx
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
category = issue


[github:pull]
raw_index = github_pulls_chaoss
enriched_index = github_pulls_chaoss_enriched
api-token = xxx
sleep-for-rate = true
no-archive = true
category = pull_request
sleep-time = 300

[github:repo]
raw_index = github_repo_raw
enriched_index = github_repo_enriched
api-token = xxx
sleep-for-rate = true
no-archive = true
category = repository
sleep-time = 300

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git-aoc_demo_enriched
out_index = git-onion_demo_enriched
contribs_field = hash
```
Kindly suggest me ,what is the reason behind this.
Thanks

**Comment by zhquan** [comment]
Hi @shikha0208,

Make sure the ElasticSearch is reachable `localhost:9200`.
If ElasticSearch is reachable try to get the indexes `localhost:9200/_cat/indices`

Best,
Quan

**Comment by shikha0208** [comment]
Hi @zhquan ,

Thank you for the reply.
Could you please tell me  how index is given with reference to what?
Like for examples below 
For github ,it is `github_demo_raw `and `github_demo_enriched`
 And for github:pull it is ,
raw_index =` github_pulls_chaoss`
enriched_index = `github_pulls_chaoss_enriched` 

How these specific names are given to index?

```
[github]
api-token = xxx
raw_index = github_demo_raw
sleep-for-rate = true
sleep-time = "300"
enriched_index = github_demo_enriched
category = issue


[github:pull]
raw_index = github_pulls_chaoss
enriched_index = github_pulls_chaoss_enriched
api-token = xxx
sleep-for-rate = true
no-archive = true
category = pull_request
sleep-time = 30
```

**Comment by vchrombie** [comment]
Hi @shikha0208 

> Could you please tell me how index is given with reference to what?

The index names are configured in the setup.cfg file. 

> For github ,it is `github_demo_raw `and `github_demo_enriched`
> And for github:pull it is ,
> raw_index =` github_pulls_chaoss`
> enriched_index = `github_pulls_chaoss_enriched`

Yes, you have actually mentioned in your comment.

> How these specific names are given to index?
> 
> ```
> [github]
> api-token = xxx
> raw_index = github_demo_raw <--------
> sleep-for-rate = true
> sleep-time = "300"
> enriched_index = github_demo_enriched <--------
> category = issue
> 
> 
> [github:pull]
> raw_index = github_pulls_chaoss <--------
> enriched_index = github_pulls_chaoss_enriched <--------
> api-token = xxx
> sleep-for-rate = true
> no-archive = true
> category = pull_request
> sleep-time = 30
> ```

If you change the names here, during the next enrichment the data is stored in the new indexes.

I will leave to @zhquan if he has anything more to comment on this.

**Comment by shikha0208** [comment]
Hi @vchrombie ,

As i change the index name in the setup.cfg file , the data does not load in the dashboard and i suppose there are some names of specific index already which i need to use.
As i give some other name , it does not display the data.

Kinldy check @zhquan .If you could explain this.
Thanks

**Comment by vchrombie** [comment]
Hi @shikha0208 

> As i change the index name in the setup.cfg file , the data does not load in the dashboard and i suppose there are some names of specific index already which i need to use.
> As i give some other name , it does not display the data.

Yes, I understand the issue. I think this is expected as the visualizations in the dashboard are created on the top of specific index names. If you are changing the index name, you are expected to change the specific index id in the dashboard.

If you want an easy solution, you check by reverting back the index name changes.

If you want the index name change, I have a solution for this but I'm not sure if that is the most efficient one but you can still try.
1. Export the dashboard to a JSON file using Kidash.
2. Replaces all the occurrences of the old index id with the new index id.
3. Import the dashboard from the JSON file using Kidash.

[Kidash usage](https://github.com/chaoss/grimoirelab-kidash#usage)

Let us know how it goes.
I would leave to @zhquan if he wants to add anything more.

**Comment by zhquan** [comment]
Hi @shikha0208,

When you change the name of the indexes on `setup.cfg` you have to wait for the new enriched indexes are created.
After that, you have to check if the aliases are assigned correctly to the new enriched indexes if not you have to change it manually.

Every time that you change the `setup.cfg` you have to restart the Mordred container or your change will not be applied.

 I hope it helps you.

Best,
Quan

**Comment by shikha0208** [comment]
Thank you @zhquan .

I am able to see the data on the dashboard with the right indexes.
