### ISSUE TITLE
Upgrade to elastico 7.9 stack (elasticsearch, kibana/kibiter)

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab-sirmordred#491]
Are there any plans to upgrade to elastico 7.9 stack?

What would be the required components to be touched to achieve this. Maybe we can use this issue to gather the requirements for such action.

**Comment by sduenas** [comment]
The platform works with ElasticSearch 7.x. Kibiter is still on 6.8 and maybe we don't release a newer version because there are other better options like OpenDistro, which integrates a lot of nice plugins. The platform works with OpenDistro now.

**Comment by marcofranssen** [comment]
Any instructions available somewhere for opendistro?

**Comment by sduenas** [comment]
We don't have anything yet documented. You should run opendistro with the docker compose file they have in their [installation guide](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/#sample-docker-compose-file) or following any other method you like. Configure the endopoints of sirmodred and run it. It should work.

**Comment by marcofranssen** [comment]
Thanks for your reply. Will give that a try soon. For completeness mordred `0.2.49` should be compatible?

**Comment by sduenas** [comment]
Yes, it should. If you find any problem, please open an issue and we'll try to fix it as soon as possible.

**Comment by marcofranssen** [comment]
I have created a new issue specifically for the opendistro setup #492.
