### ISSUE TITLE
HTTPError: 500 Server Error: Internal Server Error for url: https://bugzilla.kernel.org/rest/bug?limit=500&order=changeddate&include_fields=_all&last_change_time=1970-01-01T00%3A00%3A00Z

### ISSUE THREAD

**Issue by krushith7207** [chaoss/grimoirelab-sirmordred#495]
Hi ,

I have tried to analyse the https://bugzilla.kernel.org. I cannot see in dashboard and there was error described below.

********
File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status

raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://bugzilla.kernel.org/rest/bug?limit=500&order=changeddate&include_fields=_all&last_change_time=1970-01-01T00%3A00%3A00Z

*********

My projects.json 
` {
    "Zlib":{
        "git":
        [
             "https://github.com/madler/zlib"
        ],
        "github":
        [
             "https://github.com/madler/zlib"
        ],
        "github:pull":
        [
             "https://github.com/madler/zlib"
        ],
        "github:repo":
        [
             "https://github.com/madler/zlib"
        ]
       },
    "libjpeg":{
        "git":
        [
            "https://github.com/thorfdbg/libjpeg",
            "https://github.com/libjpeg-turbo/libjpeg-turbo"
        ],
        "github":
        [
            "https://github.com/thorfdbg/libjpeg",
            "https://github.com/libjpeg-turbo/libjpeg-turbo"
        ],
        "github:pull":
        [
            "https://github.com/thorfdbg/libjpeg",
            "https://github.com/libjpeg-turbo/libjpeg-turbo"
        ],
        "github:repo":
        [
            "https://github.com/thorfdbg/libjpeg",
            "https://github.com/libjpeg-turbo/libjpeg-turbo"
        ]
       },
    "apachecommonslang":{
        "git":
        [
            "https://github.com/apache/commons-lang"
        ],
        "github:repo":
        [
            "https://github.com/apache/commons-lang"
        ],
        "jira":
        [
            "https://issues.apache.org/jira/"
        ]
        },
    "linuxkernel":{
        "git":
        [
            "https://github.com/torvalds/linux"
        ],
        "github:repo":
        [
            "https://github.com/torvalds/linux"
        ],
        "bugzillarest":
        [
            "https://bugzilla.kernel.org"
        ]
       },
    "kazMath":{
        "git":
        [
            "https://github.com/Kazade/kazmath"
        ],
        "github:repo":
        [
            "https://github.com/Kazade/kazmath"
        ],
        "github":
        [
            "https://github.com/Kazade/kazmath"
        ],
        "github:pull":
        [
            "https://github.com/Kazade/kazmath"
        ]
        },
    "Dlib":{
        "git":
        [
            "https://github.com/davisking/dlib"
        ],
        "github:repo":
        [
            "https://github.com/davisking/dlib"
        ],
        "github":
        [
            "https://github.com/davisking/dlib"
        ],
        "github:pull":
        [
            "https://github.com/davisking/dlib"
        ]
    }
}

`
Setup.cfg
`[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = http://elasticsearch:9200

[es_enrichment]
url = http://elasticsearch:9200
autorefresh = true

[sortinghat]
host = mariadb
user = root
password =
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = http://kibiter:5601
kibiter_version = 6.1.4-1
gitlab-issues = true
gitlab-merges = true
github-repos = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

[bugzillarest]
raw_index = bugzillarest_raw
enriched_index = bugzillarest_enriched
no-archive = true

#[bugzilla]
#raw_index = bugzilla_raw
#enriched_index = bugzilla_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[github:repo]
raw_index = github_repo_raw
enriched_index = github_repo_enriched
api-token = xxxxx
category = repository
sleep-for-rate = true
no-archive = true

[gitlab:issue]
api-token = xxxxx
raw_index = gitlab_issue_raw
enriched_index = gitlab_issue_enriched
sleep-for-rate = true
category = issue
no-archive = true

[gitlab:merge]
api-token = xxxxx
raw_index = gitlab_merge_raw
enriched_index = gitlab_merge_enriched
sleep-for-rate = true
category = merge_request
no-archive = true

[github]
raw_index = github_issues_raw
enriched_index = github_issues_enriched
api-token = xxxxx
sleep-for-rate = true
no-archive = true
category = issue
sleep-time = 300

[github:pull]
raw_index = github-pull_raw
enriched_index = github-pull_enriched
api-token = xxxxx
category = pull_request
sleep-for-rate = true
no-archive = true

[jira]
raw_index = jira_raw
enriched_index = jira_enriched
no-archive = true
backend-user = xxxxx
backend-password = xxxxx

#[pipermail]
#raw_index = pipermail_raw
#enriched_index = pipermail_enriched

#[mediawiki]
#raw_index = mediawiki_demo_raw
#enriched_index = mediawiki_demo_enriched
#no-archive = true

#[meetup]
#raw_index = meetup_demo_raw
#enriched_index = meetup_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = "300"

#[stackexchange]
#raw_index = stackexchange_demo_raw
#enriched_index = stackexchange_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[slack]
#raw_index = slack_demo_raw
#enriched_index = slack_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true

#[supybot]
#raw_index = supybot_demo_raw
#enriched_index = supybot_demo_enriched

#[twitter]
#raw_index = twitter_demo_raw
#enriched_index = twitter_demo_enriched
#api-token = <YOUR_API_TOKEN_WHERE>
#no-archive = true
#sleep-for-rate = true
#sleep-time = 300

## studies based on enriched indexes

[enrich_demography:git]

[enrich_areas_of_code:git]
in_index = git_demo_raw
out_index = git-aoc_demo_enriched

[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
`
GET _cat/aliases
<img width="760" alt="Screenshot 2020-11-04 at 6 19 05 PM" src="https://user-images.githubusercontent.com/33978241/98144353-99f30600-1eca-11eb-8e08-fd58b303dda7.png">

GET _cat/indices
<img width="808" alt="Screenshot 2020-11-04 at 6 22 24 PM" src="https://user-images.githubusercontent.com/33978241/98144637-c4dd5a00-1eca-11eb-9e8e-24b9ecc4ffba.png">

GET _alias
<img width="727" alt="Screenshot 2020-11-04 at 6 23 23 PM" src="https://user-images.githubusercontent.com/33978241/98144977-f0604480-1eca-11eb-8709-110e7a68d105.png">

GET bugzillarest_enriched/_search
<img width="652" alt="Screenshot 2020-11-04 at 6 24 41 PM" src="https://user-images.githubusercontent.com/33978241/98145344-2271a680-1ecb-11eb-9b01-4e19d094421e.png">

GET bugzillarest_raw/_search
<img width="677" alt="Screenshot 2020-11-04 at 6 26 00 PM" src="https://user-images.githubusercontent.com/33978241/98145653-51881800-1ecb-11eb-8f5d-9415264e03ec.png">

**Comment by zhquan** [comment]
Hi @krushith7207,

Use `bugzilla` instead of `bugzillarest` and try again.

projects.json
```
{
    ...
    ...
    "bugzilla": [
        "https://bugzilla.kernel.org"
    ],
    ...
    ...
}
```

setup.cfg
```
#[bugzillarest]
#raw_index = bugzillarest_raw
#enriched_index = bugzillarest_enriched
#no-archive = true

[bugzilla]
raw_index = bugzilla_raw
enriched_index = bugzilla_enriched
no-archive = true
```

It's more readable if you use `Insert code` (select the code and click on `<>`) when you copy log, setup, JSON, etc.
- Click on `<>` and writing the code: only if you have one line
- Write the code, then select the code, and finally click on `<>`: for multiple lines

Best,
Quan

**Comment by krushith7207** [comment]
Hi @zhquan ,

Thanks for the reply.
It solved my problem when I selected [bugzilla] instead of [bugzillarest].
