### ISSUE TITLE
Per-project collections/enrichment

### ISSUE THREAD

**Issue by Alch-Emi** [chaoss/grimoirelab-sirmordred#511]
Howdy!

I'm currently working [on a project][Mystic Coordinator] that calls sirmordred as a library.  We're anticipating a usecase involving many projects each with several backends, with frequent changes to the projects.json.  By calling a single backend at a time, we've been able to reduce the time spent on redundant requests a good bit, but we still need to run a whole backend in order to update a single change in a single repository — a problem that grows worse as scale grows.

This is a problem that I would anticipate I'm not alone in having.  Anyone with a big enough projects.json file, especially those using micromordred, would be forced to load entire backends (a very long running task) in order to perform simple updates.

A potential solution to this would be to allow specifying an optional `project` or `repository` parameter on each relevant `Task` to restrict the scope of the task.  This functionality could easily be extended to micromordred by introducing a `--projects` parameter similar to the existing `--backends` parameter, and could eventually even be extended to the daemon by diffing each change to the `projects.json` file and rerunning only the parts that have changed.

If this is behavior that you think Mordred could benefit from, I'd be happy to write a PR.

If you have any feedback or ideas for other ways this functionality could be implemented, I'd love to hear your feedback! 

[Mystic Coordinator]: https://opensource.ieee.org/rit/mystic-coordinator

**Comment by Alch-Emi** [comment]
As a note, [a related discussion was held in the CHAOSS slack][1]

[1]: https://chaoss-workspace.slack.com/archives/C022NPTPC8Z/p1627342857054900

**Comment by sduenas** [comment]
Have you give a try to [King Arthur](https://github.com/chaoss/grimoirelab-kingarthur/)? It only schedules the part of retrieving data using perceval.

It's not yet integrated with the full platform but at some point, it will be. I hope we can start soon working on it. After that we want to design a better system to enrich data.

**Comment by Alch-Emi** [comment]
Oh thanks for the link!  That definitely seems like a really good resource, and I can't wait to see it develop a little further along.  Unfortunately it doesn't quite fill the whole use case we need it for as it is right now, since we need to be able to schedule enrichment as well.  I still think it might not hurt to add the ability to mordred itself, if you don't think it's too far out of scope

**Comment by Alch-Emi** [comment]
I just pushed a new branch which implements this behavior.  It doesn't look like it should introduce too much burden to maintenance, but I'll still wait for your call before opening a PR. 

https://github.com/Alch-Emi/grimoirelab-sirmordred/commit/851a83792c62f22b3ce6b2bff786b7c5210825df

**Comment by Alch-Emi** [comment]
Is this something that would be worth opening a PR for?

**Comment by zhquan** [comment]
Hi @Alch-Emi 

Sorry for the late reply.
We reviewed your branch and it looks interesting. Please open a PR.

Thank you very much.

Best,
Quan
