### ISSUE TITLE
[config]  Per-URL conditional perceval parameters, AKA multiple hosts for a single backend

### ISSUE THREAD

**Issue by Alch-Emi** [chaoss/grimoirelab-sirmordred#514]
As far as I know, sirmordred doesn't currently support connecting to multiple different hosts of the same backend kind.  That is to say, it is not currently possible to have a projects.json file that collects from both an `opensource.ieee.org` repository and a `gitlab.com` repository, and same for Mattermost, and potentially gitea once it's added (although this isn't a comprehensive list, and there might be more backends that would benefit from this).

This issue seems to stem from the fact that the config files can only apply config options to all requests of a backend.  Because of this, only one API key can be used per-backend/category.

I'm interested in implementing a solution to this, but I wanted to 1) ask for the blessing of the grimoirelab committers, and 2) ask about the best way to go about implementing this.

As far as I can tell, perceval parameters come from two main places:

1. The [`get_perceval_params_from_url`][1] section of grimoirelab-elk
2. The [`_compose_perceval_params`][2] method in sirmordred

The second option seems to be the most reasonable place to work, since grimoirelab-elk doesn't have access to the config.  I'm imagining a loop that checks a mapping of domains to either parameters (`("--api-key", "S0M3VAL")`), or just api keys, and applies these to the params list.

The two main questions I have would be:
- How should this fit into the config file?  It doesn't seem like ConfigParser supports passing Dicts in the config, so mappings would need to be either two lists (one of keys, one of values) that get zipped together, or a whole new config section.
- Should the implementation allow passing arbitrary parameters at the cost of making the config more complicated, or should it be limited to API keys?

As a footnote, there's another obstacle with `gitlab` not being able to detect the `enterprise-url` parameter during [`get_perceval_params_from_url`][1] like other similar backends, but that's an issue for another PR.

Thanks for any feedback!

[1]: https://github.com/chaoss/grimoirelab-elk/blob/00b346623d8f3f0b4de901d25a0ef28e79a02545/grimoire_elk/raw/elastic.py#L135
[2]: https://github.com/chaoss/grimoirelab-sirmordred/blob/cc6f81eb8573dee9202a35ea4449ede9c83856e6/sirmordred/task.py#L136

**Comment by zhquan** [comment]
Hi @Alch-Emi,

SirMordred can fetch from different hosts but you have to add different sections using tag names. 
For instance: You have two mattermost instances.

projects.json
```
{
  "GrimoireLab": {
    "mattermost:first": [
      "...",
      "..."
    ],
    "mattermost:second": [
      "...",
      "..."
    ]
  }
}
```

setup.cfg
```
[mattermost:first]
raw_index = mattermost_raw
enriched_index = mattermost_enriched
apit-token = aaa

[mattermost:second]
raw_index = mattermost_raw
enriched_index = mattermost_enriched
api-token = bbb
```

This way you can fetch both instances but using the same raw and enriched indexes.

> As a footnote, there's another obstacle with GitLab not being able to detect the enterprise-url parameter during get_perceval_params_from_url like other similar backends, but that's an issue for another PR.

Yes, that's right. Currently, if you want to fetch from enterprise you have to add it to the setup.cfg `enterprise-url` as you know. And that means all repositories under that section belong to the enterprise. Again if you want to fetch repos from both (enterprise and gitlab.com) you have to use the tag name.

I hope it helps you.

Best,
Quan

**Comment by Alch-Emi** [comment]
Oh thank you!  That's very helpful!  Would you still be interested in some sort of a change to automatically handle this?  I'm offering mostly because for my usecase, I'd end up writing something like that regardless, and it might be something that other people could benefit from.  Of course, now that I know that this is possible through this method, I can do it in my code, but there's still a few reasons it might be nicer to have a different system, namely that:

- I'm planning on supporting a pretty diverse set of backends, which would mean having at least four `[gitlab]` sections, and needing to add two more for each additional gitlab host we wanted to support
- I'm hoping to have some code to automatically detect which kind of GitLab/mattermost/etc repo is being used anyway, which would take some more configuration on my end, but it would be nice if that could be smoothly integrated with grimoirelab.

This would still have the benefit to the more standard GrimoireLab usecase in that it would be easier and cleaner for users to configure, and they wouldn't need to worry about marking labels for each backend.  Of course, I totally respect your right to mark this as out-of-scope if you decide, but I wanted to at least make my pitch :p
