### ISSUE TITLE
[config]  Simplifying configuration with inheritance

### ISSUE THREAD

**Issue by Alch-Emi** [chaoss/grimoirelab-sirmordred#515]
Following issue #514, I discovered that it was possible to support multiple hosts using the same backend, even if they use different API keys or other config parameters.  The only issue is that this can cause config files to quickly grow in size.  For example, the configuration for a gitlab backend supporting two possible hosts requires the following configuration file:

```ini
[gitlab:flagship-issue]
api-token = aabbccdd1234
raw_index = gitlab_issues_raw
enriched_index = gitlab_issues_enriched
no-archive = true
sleep-for-rate = true

[gitlab:flagship-merge]
api-token = aabbccdd1234
raw_index = gitlab_merges_raw
enriched_index = gitlab_merges_enriched
no-archive = true
category = merge_request
sleep-for-rate = true

[gitlab:ieee-issue]
api-token = ppqqrrss9876
raw_index = gitlab_issues_raw
enriched_index = gitlab_issues_enriched
no-archive = true
sleep-for-rate = true
enterprise-url = https://opensource.ieee.org

[gitlab:ieee-merge]
api-token = ppqqrrss9876
raw_index = gitlab_merges_raw
enriched_index = gitlab_merges_enriched
no-archive = true
category = merge_request
sleep-for-rate = true
enterprise-url = https://opensource.ieee.org
```

I think it's possible to simplify this without compromising intuitive by allowing backends with params to inherit from the root backend config section.  With this method, the same exact config could look like:

```ini
[gitlab]
api-token = aabbccdd1234
no-archive = true
sleep-for-rate = true

[gitlab:ieee]
api-token = ppqqrrss9876
enterprise-url = https://opensource.ieee.org

[gitlab:merge]
raw_index = gitlab_merges_raw
enriched_index = gitlab_merges_enriched
category = merge_request

[gitlab:issue]
raw_index = gitlab_issues_raw
enriched_index = gitlab_issues_enriched
```

Now, a backend with the type `gitlab:ieee:merge` could be created that would take the API token from the ieee section, the merge index from the merge section, and the default parameters from the main section.  In fact, this config would work exactly the same as the earlier config, with the added bonus of being much more readable, and (imo) more intuitive as well.  This could theoretically be compressed even smaller by merging the `[gitlab:issue]` section into the `[gitlab]` section, but I separated them for clarity here.

Additionally, this change wouldn't break backwards compatibility, since the 1st (and current) config is a completely valid config under the second section, and would produce the exact same result.

At some point, this system might even be used to support default parameters, so the config could be further reduced to

```ini
[gitlab]
api-token = aabbccdd1234

[gitlab:ieee]
api-token = ppqqrrss9876
enterprise-url = https://opensource.ieee.org
```

, although that might be for another issue.

I'll admit to having personal reasons for wanting a system like this, if it wasn't already clear.  As described in #514, I'm trying to implement a system that expects to have a large number of hosts with the same backend type, and specifically gitlab/gitea backends.  A config setup like this would make maintaining a system like this *much* easier.

I'm of course happy to implement this myself given the go-ahead.  I'm imagining a change to [`get_backend_sections()`][1] to produce a lazily generated mapping of backends with parameter combinations to the full computed parameters for that backend.  

Of course, as always, I'm open to suggestions, to concept, implementation, and anything else! 

[1]: https://github.com/chaoss/grimoirelab-sirmordred/blob/5f55af25225ce501280e3b0fcbd23d6fbb157ffc/sirmordred/config.py#L519

**Comment by vchrombie** [comment]
Hi @Alch-Emi, thanks for opening the issue. The issue looks promising and reports a genuine problem.

From my understanding and reading the issue, I'm still confused and not sure of how a `projects.json` file would look like with your proposed configurations.

The `projects.json` and `setup.cfg` should have the configuration aligned. Example from @zhquan's comment https://github.com/chaoss/grimoirelab-sirmordred/issues/514#issuecomment-893550037

projects.json
```
{
  "GrimoireLab": {
    "mattermost:first": [
      "...",
      "..."
    ],
    "mattermost:second": [
      "...",
      "..."
    ]
  }
}
```

setup.cfg
```
[mattermost:first]
raw_index = mattermost_raw
enriched_index = mattermost_enriched
api-token = aaa

[mattermost:second]
raw_index = mattermost_raw
enriched_index = mattermost_enriched
api-token = bbb
```

As you can see, `mattermost:first` and `mattermost:second` have some different configurations (`api_token`). The current implementation gives us a fine-grained control over collecting the data. Yeah, the trade-off is a long list of configurations which is, sometimes, confusing.

An _off-topic_, we developed bestiary keeping this problem in mind and currently working on it's new version [unicorn branch](https://github.com/chaoss/grimoirelab-bestiary/tree/unicorn).

I would like to see comments and views from the community members as well. :slightly_smiling_face:

**Comment by Alch-Emi** [comment]
If I understand your question correctly, then the `projects.json` would look exactly the same.  The main difference would be that some parameters can be specified for an entire backend.  In your example, you could still finely control the api token of each mattermost instance.  The `setup.py` would look something like:

```ini
[mattermost]
raw_index = mattermost_raw
enriched_index = mattermost_enriched

[mattermost:first]
api-token = aaa

[mattermost:second]
api-token = bbb
```

While the `projects.json` would still look like

```json
{
  "GrimoireLab": {
    "mattermost:first": [
      "...",
      "..."
    ],
    "mattermost:second": [
      "...",
      "..."
    ]
  }
}
```

The difference is that when a task accesses the `mattermost:first` backend, instead of just returning the `mattermost:first` section, mordred could load the `mattermost` section, and then `update()` it with the contents of `mattermost:second`.  In this way, backend parameters act like tags that can be used to add new config options to the generic/base backend.

Also, the `projects.json` and `setup.cfg` from zhquan's comment (as well as any configs from before the change) would still work the same under the proposed system, since composing an empty `[mattermost]` section with a fully detailed `[mattermost:first]` section would produce the same result.

**Comment by sduenas** [comment]
One of our objectives for this year is to have ready [bestiary](https://github.com/chaoss/grimoirelab-bestiary/tree/unicorn) which will solve all of these problems. Bestiary will be the main component where information about datasources will be stored. This means, `projects.json` will be abandoned and some parts of the configuration of mordred will be deprecated too.

I wouldn't like to put effort trying to solve this issue in Mordred when we have a new component that will do it. We'll be very happy if you want to collaborate with it @Alch-Emi and give your ideas about it, although I understand it doesn't solve your problem now.

**Comment by Alch-Emi** [comment]
To be clear, I'm volunteering to write this change myself, I'm just looking for permission to write the PR.  But either way, it sounds like I should learn a little more about bestiary before anything else.  I spun up a local `unicorn` instance, and have been messing around with it a little bit, but I still have a couple questions about what CHAOSS's goals for the project are.  I shot you a message on Slack if you wanted to talk about it without needing to do the back-and-forth over GitHub issues, if you're interested.
