### ISSUE TITLE
Connections to the Sorting Hat database are not closed

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab-sirmordred#525]
Currently, Sirmordred enrichment doesn't close the connections to Sorting Hat.

When Sirmordred creates a Database for SortingHat (https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_enrich.py#L68), it creates an engine with a pool of 25 connections: https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/db/database.py#L198

Whenever it is called to
```
engine.connect().close()
```
it is not closing the connection, it is storing the connection in the engine pool with the sleep command to be reused by a future query:
```
+-----+------+------------------+---------+---------+------+-------+------------------+----------+
| Id  | User | Host             | db      | Command | Time | State | Info             | Progress |
+-----+------+------------------+---------+---------+------+-------+------------------+----------+
| 124 | root | 172.25.0.1:59782 | test_sh | Sleep   |  423 |       | NULL             |    0.000 |
```
Connections are closed when (for example) micro mordred finishes the execution, but if the function is called from an external program, in an infinite loop, that program is unable to close the connections because doesn't have a reference to the engine, and the connection keeps open until the database decides to close the connection.

The same happens when ELK creates an engine in SortingHat (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L132), it is never closed/disposed.

I think there are two ways of closing the connections:
- Disable pooling in the engine, that way every time a connection is closed it is not returned to the connection pool, and it is really closed.
- Create a method in the Database class to stop using it. That method can call to engine.dispose() and close all the connections in the pool. That new method should be called in ELK and Sirmordred when they finish their tasks with the Database.

**Comment by sduenas** [comment]
Why do we need to close connections? The idea is to have the pool because we are constantly using them. Otherwise, you would have to open and close them most of the time. What's the problem to keep them opened?
