### ISSUE TITLE
Cannot index gitlab issues from gitlab-com project

### ISSUE THREAD

**Issue by Gnafu** [chaoss/grimoirelab-sirmordred#528]
Hi,
I'm trying to index the following issues: 
https://gitlab.com/gitlab-com/marketing/community-relations/evangelist-program/general/-/issues
but I get no data and no errors in the logs.

In my projects.json I have:
```
    	"gitlab:issues": [
            "https://gitlab.com/gitlab-com/marketing%2Fcommunity-relations%2Fevangelist-program%2Fgeneral",
            "https://gitlab.com/Gnafu/docker-geoserver"
        ]
```

I can see 3 indexed issues (they appeared when I added the second line for testing) but 0 indexed if I use only the first line.
May that be related to the fact that the owner is "gitlab-com" ?
The following URLs fails with a 404:

```
            "https://gitlab.com/gitlab-com/marketing/community-relations%2Fevangelist-program%2Fgeneral"
            "https://gitlab.com/gitlab-com%2Fmarketing%2Fcommunity-relations%2Fevangelist-program%2Fgeneral"
```

Is there a full working example I can use to get gitlab issues and merge requests?

Thank you

**Comment by vchrombie** [comment]
Hello @Gnafu, thanks for using GrimoireLab and opening this issue for clarifying the doubts.

> In my projects.json I have:
> ```
>     	"gitlab:issues": [
>             "https://gitlab.com/gitlab-com/marketing%2Fcommunity-relations%2Fevangelist-program%2Fgeneral",
>             "https://gitlab.com/Gnafu/docker-geoserver"
>         ]
> ```
> I can see 3 indexed issues (they appeared when I added the second line for testing) but 0 indexed if I use only the first line. May that be related to the fact that the owner is "gitlab-com"?


> The following URLs fails with a 404:
> ```
>             "https://gitlab.com/gitlab-com/marketing/community-relations%2Fevangelist-program%2Fgeneral"
>             "https://gitlab.com/gitlab-com%2Fmarketing%2Fcommunity-relations%2Fevangelist-program%2Fgeneral"
> ```



> Is there a full working example I can use to get gitlab issues and merge requests?

**Comment by Gnafu** [comment]
Thank you @vchrombie ,
I let it run for the night and came back to the harvested issues.

The logs states that the collection started after 1h 45m and, after a few milliseconds :
``` Collection for gitlab:issues: finished after 00:43:30 hours ```

So I suspect the logging system delayed a bit and the collection actually started 1h after the startup, lasting 43 minutes.
After that, other collections took 18 seconds top.

It is worth noting I'm running grimoirelab on a VM (4CPU, 9GB RAM)

Also for completeness, here's my setup.cfg config:
```
[gitlab:issues]
api-token = REDACTED
raw_index = gitlab_issues_demo_raw
enriched_index = gitlab_issues_demo_enriched
no-archive = true
#enterprise-url = <YOUR_GITLAB_INSTANCE_URL>
sleep-for-rate = true
```

**Comment by vchrombie** [comment]
Looks like the execution went fine when you gave ~some~ lot of time :sweat_smile: 
Were you able to see the dashboards?

Please feel free to close the issue if the problem is fixed.

Also, the `setup.cfg` configurations looks fine to me.

**Comment by Gnafu** [comment]
Yes, I was able to see the dashboards filled with data, it was just a matter of time.
I suggest to add some kind of indicator about the collection status in the UI because even the logs were not showing any information about the issues being "not yet collected".

I'm closing this, thank you.

**Comment by vchrombie** [comment]
> Yes, I was able to see the dashboards filled with data, it was just a matter of time. I suggest to add some kind of indicator about the collection status in the UI because even the logs were not showing any information about the issues being "not yet collected".

That's great to hear.

We have added this message at some places across the grimoirelab repo and the tutorial
```
Your dashboard will be ready after a while at http://localhost:5601. The waiting time depends on the 
amount of data to fetch from a repo, for small repositories you can expect your data to be visible in the 
dashboard after 10-15 minutes.
```
- https://github.com/chaoss/grimoirelab#using-docker-compose
- https://chaoss.github.io/grimoirelab-tutorial/docs/getting-started/setup/#steps

@Gnafu do you have any suggestion where we can add more info?

BTW, thanks for closing the issue.
