### ISSUE TITLE
Getting all projects from enterprise Gitlab

### ISSUE THREAD

**Issue by phdesro** [chaoss/grimoirelab-sirmordred#530]
Hi, my company is looking to use GrimoireLab. We would like to not have to generate a projects.json but simply use our enterprise-url and gitlab token to get all of our projects.

We would like some feedback to see how easy it would be to implement. We're able to do the work ourselves, but would like opinions on how to implement it cleanly/easily.

Thanks!

**Comment by vchrombie** [comment]
> Hi, my company is looking to use GrimoireLab. We would like to not have to generate a projects.json but simply use our enterprise-url and gitlab token to get all of our projects.

GrimoireLab works on the configuration files like `projects.json` and `setup.cfg`. I understand your usecase though. I assume your team doesn't want to take the effort of updating the `projects.json`. If I'm right, you can write a script which fetches the project urls using the gitlab API & token and write them to the `projects.json` which is the most simplest way.

> We would like some feedback to see how easy it would be to implement. We're able to do the work ourselves, but would like opinions on how to implement it cleanly/easily.

I feel many things might break and you might end up rewriting a lot of implementations. But, if are willing to proceed, please let us know if you need any help from our side.

[sirmordred/task_projects.py](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/task_projects.py) deals with extracting the projects from the json file.

**Comment by phdesro** [comment]
Thanks for the quick feedback, this is the solution we're currently investigating (the script). Will update you if we decide to process with the changes.

**Comment by phdesro** [comment]
I have another question not linked to this issue, would it be better to create another one?

**Comment by vchrombie** [comment]
Please feel free to open a new issue if it is a different topic.

**Comment by jjmerchante** [comment]
Closing this ticket due to inactivity. Don't hesitate to reopen the ticket if you have any other questions.
