### ISSUE TITLE
[utils] Can't find `menu.yaml` and `aliases.json` in `/sirmordred`

### ISSUE THREAD

**Issue by TieWay59** [chaoss/grimoirelab-sirmordred#538]
### Digest

I followed the [Getting-Started](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#source-code-and-docker-) tutorial running `micro.py` in `/sirmordred`. The log tells that it can't find `../aliases.json`.

@vchrombie helped to investigate this. According commit https://github.com/chaoss/grimoirelab-sirmordred/commit/680099a5d4b3c60725eba0166eed42e854d1dd3b `/utils` directory is moved to `/sirmordered/utils` including `/utils/setup.cfg`. This file link to two external files `../menu.yaml` and `../aliases.json` which are not moved into `/sirmordered` relatively caused this issue. 

https://github.com/chaoss/grimoirelab-sirmordred/blob/8a8bb8de7e914b60bdfcbf0c074fda345236c7b2/sirmordred/utils/setup.cfg#L27-L28

Now the `aliases.json` and `menu. yaml` are still in the root of the repository.

###  Environment

```bash
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
# python -V
Python 3.7.13
# poetry -V
Poetry version 1.1.13
# git log
commit 8a8bb8de7e914b60bdfcbf0c074fda345236c7b2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 77b1d6b 4c50130
Author: Quan Zhou <quan@bitergia.com>
Date:   Tue Mar 29 10:11:21 2022 +0200

    Merge branch 'dynamic' of 'https://github.com/xiao623/grimoirelab-sirmordred'
    
    Merges #534
    Closes #534
```

### Possible solution

I moved the `aliases.json` and `menu.yaml` into their palce and everything work as expected.

### Other questions

Hi @jjmerchante, Does `aliases.json` and `menu.yaml` in root directory are left intently? Will anything else break if I just move these two into `/sirmordered` ?

Are there any other files left accidently if so? I can help PR and repair this.

**Comment by vchrombie** [comment]
Thanks for opening the issue @TieWay59 

> Hi @jjmerchante, Does `aliases.json` and `menu.yaml` in root directory are left intently? Will anything else break if I just move these two into `/sirmordered` ?

From what I understand, the `aliases.json` and `menu.yaml` can be in the root of the repository. I would suggest to update the configurations in the `setup.cfg` file.

**Comment by TieWay59** [comment]
Thanks, @vchrombie, I agree with you, but there are only two of us who reviewed this issue.

I don't know if GitHub @ is the best way to remind others. I'll wait until tomorrow ends, and if no other opinion is received, I'll just start the PR working on it.
