### ISSUE TITLE
[requirements.txt] No matching distribution found for grimoireelk

### ISSUE THREAD

**Issue by TieWay59** [chaoss/grimoirelab-sirmordred#558]
When running `pip install -r requirements.txt` I found that the grimoireelk installing reported an error.

https://github.com/chaoss/grimoirelab-sirmordred/blob/c21040825258c1d9d33e15d1c544795fb4db6226/requirements.txt#L8

### Reproduction

Clone this repo (and download all the forks according to the tutorial teaches) and run `pip install -r requirements.txt`

This might take a long time, here I have a smaller case:

run `pip install "grimoireelk @ git+https://github.com/chaoss/grimoirelab-elk@master"`

```shell
Collecting grimoireelk@ git+https://github.com/chaoss/grimoirelab-elk@master
  Cloning https://github.com/chaoss/grimoirelab-elk (to revision master) to /tmp/pip-install-c4wxzdz4/grimoireelk_8cd586cb149240daba3db725490e59ae
  Running command git clone --filter=blob:none --quiet https://github.com/chaoss/grimoirelab-elk /tmp/pip-install-c4wxzdz4/grimoireelk_8cd586cb149240daba3db725490e59ae
  Resolved https://github.com/chaoss/grimoirelab-elk to commit 058d82ed5aabbbd23536b985266fdc02f292fdd5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package grimoireelk produced metadata for project name grimoire-elk. Fix your #egg=grimoireelk fragments.
Discarding git+https://github.com/chaoss/grimoirelab-elk@master: Requested grimoire-elk from git+https://github.com/chaoss/grimoirelab-elk@master has an inconsistent name: filename has 'grimoireelk', but metadata has 'grimoire-elk'
ERROR: Could not find a version that satisfies the requirement grimoireelk (unavailable) (from versions: none)
ERROR: No matching distribution found for grimoireelk (unavailable)
```

### Possible solution

According to `setup.py` in https://github.com/chaoss/grimoirelab-elk, we can find its module name is `grimoire-elk` and `grimoireelk` might be a typo originally introduced from https://github.com/chaoss/grimoirelab-sirmordred/commit/bbe05fbca2592833afc6e29c3602e18ec58598a5.

```python
# copied from https://github.com/chaoss/grimoirelab-elk/blob/058d82ed5aabbbd23536b985266fdc02f292fdd5/setup.py#L41-L42

setup(name="grimoire-elk",
      description="GrimoireLab library to produce indexes for ElasticSearch",
```

### Disscution

> In future releases requirements.txt file will be deprecated and poetry will be used so this is a temporal fix. https://github.com/chaoss/grimoirelab-sirmordred/commit/bbe05fbca2592833afc6e29c3602e18ec58598a5  #531 

Hi @jjmerchante, I understand that `requirements.txt` is not recommended anymore. However, I wonder if I could fix this typo in this main version of the sirmordred and keep it neat to install the dependencies? I find it quite error-prone if we follow the current tutorial without taking notice of it.

**Comment by TieWay59** [comment]
BTW: The best practice to install dependency is `pip install poetry` + `poetry install`, I agree that poetry is much faster and nicer to handle.

**Comment by vchrombie** [comment]
`Discarding git+https://github.com/chaoss/grimoirelab-elk@master: Requested grimoire-elk from git+https://github.com/chaoss/grimoirelab-elk@master has an inconsistent name: filename has 'grimoireelk', but metadata has 'grimoire-elk'`

> According to `setup.py` in https://github.com/chaoss/grimoirelab-elk, we can find its module name is `grimoire-elk` and `grimoireelk` might be a typo originally introduced from [bbe05fb](https://github.com/chaoss/grimoirelab-sirmordred/commit/bbe05fbca2592833afc6e29c3602e18ec58598a5).

Yes, you are right @TieWay59. The issue is because of the typo. Please feel free to open a PR for this.
