### ISSUE TITLE
Is it possible to add more than a label to the repositories

### ISSUE THREAD

**Issue by canasdiaz** [chaoss/grimoirelab-sirmordred#571]
In the documentation I can read:
 * Label --labels=[example]: The data source will have the label of example which can be used to create visualizations for specific sets of data

Is it possible to add more than a label? How do they must be separated?

**Comment by jjmerchante** [comment]
Hi @canasdiaz 

Yes, it is possible to add more than one label with the following format:
```
http://example.com --labels=[A, B, C]
```

The important detail is that the labels are separated by commas.

Feel free to reopen the ticket if you have any other questions.
