### ISSUE TITLE
How to skip lfs object when clonging project

### ISSUE THREAD

**Issue by g0tbread** [chaoss/grimoirelab-sirmordred#575]
Hello
  Due to the lfs files of the project are too large, thus it often causes a timeout error：
mordred_1        | error: 4536 bytes of body are still expected
mordred_1        | fetch-pack: **unexpected disconnect while reading sideband packet**
mordred_1        | fatal: early EOF
mordred_1        | fatal: index-pack failed

How to clone but ignore lfs object when executing the command:
     micro.py --raw --enrich --cfg /home/bitergia/conf/setup.cfg --backends git
  or 
     There is a configuration that can specify to ignore lfs?
Thanks

**Comment by sduenas** [comment]
We don't have any kind of configuration for doing that. I'm not sure what the status of LFS is on git project. According to some articles I've been reading, `git lfs clone` and `git clone` are the same thing now. To avoid cloning big files there's something called **partial clone**. Maybe you can try to modify the code and see if it works. On this [GitLab doc](https://docs.gitlab.com/ee/topics/git/partial_clone.html) and on this [GitHub article](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) you can find more info about how to run this.

The piece of code you will have to modify is [this one](https://github.com/chaoss/grimoirelab-perceval/blob/f7cec4254eac3e10c4c75d54b9d5c4d6d88ccd6e/perceval/backends/core/git.py#L836)

I can try these by myself if you give me the details about how to clone that repository.

**Comment by g0tbread** [comment]
> 

Thanks for your reply  : - )
The command I want to be executed is ：  GIT_LFS_SKIP_SMUDGE=1 git clone SERVER-REPOSITORY
I will give a try to change piece of code to see if it is works：
cmd = [‘GIT_LFS_SKIP_SMUDGE=1’, 'git', 'clone', '--bare', uri, dirpath]

**Comment by sduenas** [comment]
The `GIT_LFS_SKIP_SMUDGE` env variable should be defined in here: https://github.com/chaoss/grimoirelab-perceval/blob/f7cec4254eac3e10c4c75d54b9d5c4d6d88ccd6e/perceval/backends/core/git.py#L839

**Comment by g0tbread** [comment]
Hi,@sduenas
I tried to add the GIT_LFS_SKIP_SMUDGE configuration at env, but from the execution of micro.py, it did not take effect
The following is the file location information I modified:
vim /usr/local/lib/python3.8/site-packages/perceval/backends/core/git.py
         env = {
             'LANG': 'C',
             **'GIT_LFS_SKIP_SMUDGE': '1',**
             'HOME': os.getenv('HOME', '')
         }

**Comment by g0tbread** [comment]
> The `GIT_LFS_SKIP_SMUDGE` env variable should be defined in here: https://github.com/chaoss/grimoirelab-perceval/blob/f7cec4254eac3e10c4c75d54b9d5c4d6d88ccd6e/perceval/backends/core/git.py#L839

Hi，@sduenas
I fianlly found the correct configuration place：
1.First docker exec into mordred container
2.Add gitconfig for bitergia (/home/bitergia/.gitconfig)，Below is the configuration：
...skip...
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge --skip
        process = git-lfs filter-process --skip
        checkout =
        required = false
[lfs]
        fetchexclude = *
