### ISSUE TITLE
How to use arthur feature in modred?

### ISSUE THREAD

**Issue by nuriguri** [chaoss/grimoirelab-sirmordred#58]
I want to use arthur in modred~ when i check the code, i guess below code will activate arthur feature.
But it is not working. Could you let me know usage guide?

[es_collection]
url = http://localhost:9200
user =
password =
**arthur = true
arthur_url = http://127.0.0.1:8080
redis_url = http://127.0.0.1:6379**

**Comment by acs** [comment]
HI @nuriguri ,

First of all, I am sorry for the delay attending your petition. The arthur support is now in alpha stage so we don't recommend it yet for wide usage. Could you describe your use case and why do you need to use arthur instead the current approach? In any case, the arthur scenario will be our default scenario in some weeks.

The configuration you are showing must activate in any case arthur. Do you have some logs? Why do you know it is not working?

Cheers

**Comment by nuriguri** [comment]
HI @acs ,

Thanks for answering.
I tried this because arthur seemed to be a module for collecting data in the grimoire guide.
But as i know, data can be updated without arthur now.
what is different thing between collect data with arthur and witout arthur?

While wait your answer, I tried to use arthur continuously and finally succeeded.
i used below configuration,
**arthur = true
arthur_url = http://127.0.0.1:8080
redis_url = redis://localhost/8**

And , To running mordred with, i faced some problem 
The problem was below things.

1. **some of backend configuration is not working for arthur**. (ex : jira - backend-user, backend-password etc..) => I modified this thing to run temporarily. 
2. **After merge identities using sortinghat, enriched index is not updated without removing enriched inde**x. => I can't fix it now. i think it is not supported now.

I am looking forward to arthur becoming the default scenario.

Thank you.

**Comment by acs** [comment]
Hi @nuriguri,

The collection of data is done by perceval, but in order to coordinate it (download the data from all data sources) right now then options are to use GrimoireELK (the default one) and arthur (the future one). 

When you talk about the grimoire guide, are you referring to https://grimoirelab.gitbooks.io/tutorial/content/?

About your problems, yes, we are finishing the arthur integration in mordred, and there are some issues yet to be fixed. Could you open specific issues in this mordred tracker? We are going to finishing the integration of all data sources (it is just some minor adjustments in config) in arthur next weeks, and if you help us checking the whole thing, this will be awesome!

I can't understand clearly your second problem. Would you mind providing more details?

And yes, arthur will be the default scenario in some weeks!

Cheers!

**Comment by nuriguri** [comment]
Hi @acs 
I am sorry for the delay. I'll answer for your question.

1. When you talk about the grimoire guide, are you referring to https://grimoirelab.gitbooks.io/tutorial/content/?  => **Yes**
2.  Could you open specific issues in this mordred tracker? => **Can I open arthur-related problem while the arthur integration is not yet finished?**
3. if you help us checking the whole thing, this will be awesome! => **I'll try it~!**
4. I can't understand clearly your second problem. Would you mind providing more details?
=> While running mordred and arthurd & arthurw, i merged some user identity using sortinghat merge command. I expected the result to be updated with the elasticsearch enrich index through arhtur so that we could see the results in kibiter. But enriched index is not updated automatically. only after remove enrich index using "curl -XDELETE", modified result is updated. ( And I used [es_enrichment][autorefresh] = true)

Thank you.

**Comment by acs** [comment]
The arthur integration is now ready so you can open issues now in mordred related to it.

About the merging of identities, it is not covered by arthur, but GrimoireELK. In the last weeks we have improved the refreshing of identities code, so your problem could be already fixed. Could you check it?

**Comment by nuriguri** [comment]
Hi @acs 
I checked feature about  merging of identities using latest. It looks like working well. Thanks for your feedback.

**Comment by acs** [comment]
@nuriguri closing this ticket. If you have additional issues please reopen it.
