### ISSUE TITLE
Jira integration appears to be non-functional

### ISSUE THREAD

**Issue by kc-sn** [chaoss/grimoirelab-sirmordred#586]
Logs don't indicate any issue with connectivity and the Jira dashboard isn't showing my API user connecting. We are using the cloud version of Jira. The Jira dashboard component is appearing on Kibana.

Configuration as follows:

setup.cfg
```
    [jira]
    raw_index = jira_raw
    enriched_index = jira_enriched
    no-archive = true
    backend-user = xyz@domain.com
    backend-password = xyz-long-api-key
```

projects.json
```
      "devops": {
        "jira": [
            "https://company.atlassian.net --filter-raw=data.fields.project.key:DEVOPS"
        ],
        "meta": {
          "title": "Company ENG [DevOps]"
        },
        ...
```

**Comment by sduenas** [comment]
Would you mind to run perceval and post the output of the tool. Perceval is the tool that uses mordred to fetch the data from different datasources. You can find how to run it here: https://github.com/chaoss/grimoirelab-perceval/#jira
You may need to add the api token parameter.

**Comment by jjmerchante** [comment]
Closing this ticket due to inactivity. Don't hesitate to reopen the ticket if you have the requested output.
