### ISSUE TITLE
Mordred should allow to unify identities by source field

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sirmordred#85]
Recent versions of SortingHat allow us to merge accounts using different algorithms by data sources, this feature is not possible with Mordred yet. By adding this feature, we'll allow our system to get a list of github users and merge that into the identities database without side effects with usernames from other sources like IRC, where the username is not a good match indicator at all.

This is a proposal for the syntax:
`matching = [email, username:github]`

I would unify by 'email' and by 'username' only among identities where source = github.

**Comment by sanacl** [comment]
This is no longer needed by Bitergia. If no community member is interested in this I would close this ticket as wont-fix.

Anyone interested in this?

**Comment by valeriocos** [comment]
+1 @sanacl
